### ISSUE TITLE
Need some help setting this up

### ISSUE THREAD

**Issue by subby2006** [cabernetwork/cabernet#103]
I'm trying to get the docker container version set up however nothing seems to work. The ghcr version starts up but the webui is inaccessible and all of the dockerfiles fail to build.

Trying to set it up on windows after docker not working doesn't seem to work either (or maybe I'm missing something). Daddylive and EPG are enabled but going to localhost/Daddylive/channels.m3u gives me a 501 - unimplemented.

Can someone give me a beginners guide here on how to properly set this up, either as a docker or on windows?

**Comment by subby2006** [comment]
I was able to fix the docker install by changing the dockerfile python version to 3.9 as the install for rust would fail otherwise but the web panel isn’t accessible from outside.

Anyways after countless hours of trying I finally got the windows version to work but I would’ve preferred running it through docker, is there something not being forwarded like a port?

**Comment by rocky4546** [comment]
For docker, you should be using the yml file, which contains all the info.  The biggest issue is what to externally mount.  The experts say you should mount the entire app folder, but many have issues and only externally mount the plugin_ext and data folders.  If you want to look at some docker details, try #60
