### ISSUE TITLE
Can't Access Streams

### ISSUE THREAD

**Issue by elliotmarks06** [cabernetwork/cabernet#105]
I'm trying to access the Cabernet streams, and it doesn't work. I get the following error whenever I try to play something in VLC, Jellyfin, etc:

`2023-09-16 19:29:41,707-WARNING:web_handler [192.168.1.22] "GET /PlutoTV/watch/5ca6748a37b88b269472dad9 HTTP/1.1" 501 -
2023-09-16 19:29:41,862-NOTICE:web_admin UNKNOWN HTTP Request /watch/5ca6748a37b88b269472dad9`

I can bypass the error for PlutoTV by setting the stream_type to m3u8 redirect, but that isn't possible with DaddyLive. Is there something I'm doing wrong, or some way to fix the error?

Thanks,
Elliot

**Comment by rocky4546** [comment]
Normal reason would be that your plugin is disabled, so your URL for plutotv would be invalid.  I recommend increasing the logging to at least INFO to see why it is being disabled during startup.

**Comment by elliotmarks06** [comment]
I changed the logging to INFO, here's what I get at startup:
![image](https://github.com/cabernetwork/cabernet/assets/63259343/57b532ed-3ac8-4dc8-bc79-0702f4749182)

And for reference, here's my config file:
![image](https://github.com/cabernetwork/cabernet/assets/63259343/7a39b431-8d43-4e1c-8f79-f017416e1bfa)



I've tried all three stream_types and nothing works. The only error I see in the log is that it can't find streamlink (which is weird because it's installed in my path and accessable by typing "streamlink"), but that shouldn't matter unless I'm using the streamlink stream_type, right?

Thanks for your help,
Elliot

**Comment by rocky4546** [comment]
The log says your streaming port and your webUI port are the same.  So, having two web servers running on the same port will only cause the system to not work.  By default, the streaming port is 5004 and the webui port is 6077...

**Comment by elliotmarks06** [comment]
That did it! Thanks!
