### ISSUE TITLE
xmltv.xml missing document header.

### ISSUE THREAD

**Issue by TazDevilLooney** [cabernetwork/cabernet#109]
I'm having a problem importing the xmltv.xml into Matthuisman's IPTV Merge in Kodi. It seems the file is missing some header information and the app rejects it however it does import into TVHeadEnd with no issue.

Missing example........

xml version="1.0" encoding="ISO-8859-1"
DOCTYPE tv SYSTEM "xmltv.dtd"

Thanks for your time :)

**Comment by TazDevilLooney** [comment]
Oh i forgot, i'm using your latest linux addition on Debrain bullseye.

**Comment by rocky4546** [comment]
provide example xmltv.xml file

**Comment by rocky4546** [comment]
So this is associated with importing Cabernet xmltv.xml file.  What is the error on the clent side when you do the import?

**Comment by TazDevilLooney** [comment]
I tried very hard to get a log of some description but the logs showed nothing about it. I tried using the merge again and it just highlights the epg in red and no error presented. Then i thought i'd try the IPTV Simply TV client and put the information in there. Same result no error, no EPG but got some channel names and numbers, no thumb nails though. 

After a bit more digging i managed to get a send and reply from the cabernet webserver.

Client ask's for information from server -> OK
Server reply to the client was was to `|PTR| 7.2.0.10.in-addr.arpa` -> Wrong

Reply should of been 10.0.*.* so were it's sending the reply i have no idea. I tried the web but nothing exists.

I use ssh to remote to the server and that works correct. I even gave the  client and server DNS names but was still diverting to this mystery address. I guess i didn't notice before as all the software was on one unit (local host). Now i have two ( Server and Client ) This seems to be happening. 

So my assumption off an issue with the m3u and xmltc.xml seems to be incorrect. I guess to be absolutely sure i need to rework the servicer unit. All it had was Pi-4, Bebain bullseye, the  

Was Python2 stock.........
Python 3.7+
python cryptography module
python requests module
(optional) streamlink module
ffmpeg and ffprobe

and the Cabernet software unzipped in the home folder. Can't really see much to go wrong really.  I'm really busy the next few days but i'll restore it all if required. Please let me know your wishes.

Thanks for your patents regarding this. :)

**Comment by rocky4546** [comment]
I see no info to help identify the issue.  If you are using Kodi, you can turn on extreme logging.  Without some kind of info, I will not be able to help.

**Comment by AFrameWorker** [comment]
Yeah I have the same/similar issue.  Kodi just wont seem to acknowledge the EPG file(s) from cabernetwork, it simply does not work. I'm using the IPTV Simple Client.

If I use the EPG's that i.mjh.nz provide, they work just fine. If I implement them into cabernetwork and use the xmltv.xml provided by cabernetwork, then they don't work

**Comment by AFrameWorker** [comment]
[failure.txt](https://github.com/cabernetwork/cabernet/files/12883023/failure.txt)

Here's the log when it failed.

**Comment by rocky4546** [comment]
The log indicates the xmltv.xml had mismatched tags at character offset 0.
"display-name><display-name>Caught in Providence</display-name>......"
That is obviously invalid.  So, either the Kodi software is not able to read the file or the file somehow is corrupted.  The information you provided initially indicates it did receive the front matter, so it may not be a Cabernet issue.  It is possible there is some illegal character involved.  I would grab the xmltv.xml file, bring it up in an editor and look at the channel section prior to "Caught in Providence" channel.  I suspect there may be a greater than or less than sign in the channel name, but check that section.

**Comment by rocky4546** [comment]
Considering what youare doing, it might be normal.  restart cabernet and continue

**Comment by slippyC** [comment]
I can confirm this is an issue.  If header information is missing in the xlmtv.xml file then Kodi/IPTV simple doesn't like it.

<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE tv SYSTEM "xmltv.dtd">

If schema/dtd info missing then PVR IPTV Simple rejects the EPG info.
