### ISSUE TITLE
Possible to add plug-in for theTVApp? 

### ISSUE THREAD

**Issue by khthe8th** [cabernetwork/cabernet#110]
Wondering if it's possible for cabernet to work with https://thetvapp.to/tv? Would this require a new plug-in similar to the existing ones? The daddylive site seems to have lots of issues / go down a lot and tvapp website is more reliable for me and would love to be able to pipe it into plex using cabernet if possible

**Comment by rocky4546** [comment]
moved to discussion incase someone wants to create a plugin.
