### ISSUE TITLE
How to run as docker container?

### ISSUE THREAD

**Issue by bjoerns1983** [cabernetwork/cabernet#113]
Hi there,
is there any good guide how to run it as docker container with docker compose?
I followed the steps in the read me but starting it with docker compose up just gives me:

cabernet  | python3: can't open file '/app/tvh_main.py': [Errno 2] No such file or directory
cabernet exited with code 0

What am i doing wrong?

**Comment by Nostradamus1973** [comment]
Good morning,

Maybe I can help.
I think I have a sample docker-compose somewhere on the cabernet github, I certainly can post it here if you'd like. 

Personally, I use Portainer and just create a stack and then show portainer where the docker compose file is, give it a name(lowercase) and pull it, I keep my dockers in my home directory in a folder named "dockers", you can do it your own way of course; if your parameters are correct Portainer will let you know if it's a success or not and which ports it's running on.
There are some great tutorials showing how to install portainer on a variety of platforms once docker is installed.
I'm not an expert in docker, in fact I'm sorta new to it myself, I just thought I'd try to offer help through my own experience with cabernet docker.

Have a great day.

**Comment by rocky4546** [comment]
You can look at issue #60 for information.  The result of that was that the entire Cabernet product needs to the unzipped and mounted in a separate volume.  There has been some people that indicate you cannot map the volume at the /app level as shown in the [docker-compose.yml](https://github.com/cabernetwork/cabernet/blob/master/docker-compose.yml) file, so it might be good to set it up as 
volumes:
          - ./docker/cabernet/config/app/cabernet:/app/cabernet
and unzip the cabernet source into ./docker/cabernet/config/app/cabernet.  Then the entry point in the Dockerfile would change to 
ENTRYPOINT ["python3", "/app/cabernet/tvh_main.py"]

Only mounting the data area as indicated by [Nostradamus1973](https://github.com/Nostradamus1973) would cause lots of issues with the plugins and would not be recommended as stated in issue #60

**Comment by bjoerns1983** [comment]
> Good morning,
> 
> Maybe I can help. I think I have a sample docker-compose somewhere on the cabernet github, I certainly can post it here if you'd like.
> 
> Personally, I use Portainer and just create a stack and then show portainer where the docker compose file is, give it a name(lowercase) and pull it, I keep my dockers in my home directory in a folder named "dockers", you can do it your own way of course; if your parameters are correct Portainer will let you know if it's a success or not and which ports it's running on. There are some great tutorials showing how to install portainer on a variety of platforms once docker is installed. I'm not an expert in docker, in fact I'm sorta new to it myself, I just thought I'd try to offer help through my own experience with cabernet docker.
> 
> Have a great day.
> 
> EDIT: Here's my docker compose https://pastebin.com/Yag4y82N

Normally i dont need anything like Portainer. With a good docker compose there is no need for a GUI.



> You can look at issue #60 for information. The result of that was that the entire Cabernet product needs to the unzipped and mounted in a separate volume. There has been some people that indicate you cannot map the volume at the /app level as shown in the [docker-compose.yml](https://github.com/cabernetwork/cabernet/blob/master/docker-compose.yml) file, so it might be good to set it up as volumes: - ./docker/cabernet/config/app/cabernet:/app/cabernet and unzip the cabernet source into ./docker/cabernet/config/app/cabernet. Then the entry point in the Dockerfile would change to ENTRYPOINT ["python3", "/app/cabernet/tvh_main.py"]
> 
> Only mounting the data area as indicated by [Nostradamus1973](https://github.com/Nostradamus1973) would cause lots of issues with the plugins and would not be recommended as stated in issue #60

Thats a good hin. I think the readme nowhere explains that you also have to unzip the source somewhere to get it running. Also i think the part of the recommended docker file is a bit confusing.

**Comment by rocky4546** [comment]
No dev has taken on the docker install.  I try it every year or so, but rely on others to provide inputs and then make the changes.  I will make your recommended changes to the readme.
