### ISSUE TITLE
Requests lib does not support HTTP/2.0 protocols

### ISSUE THREAD

**Issue by rocky4546** [cabernetwork/cabernet#114]
Providers are sometime using HTTP/2.0 protocols and the requests library only supports upto HTTP/1.1.  The recommendation is to move to HTTPX library that supports HTTP/2.0.  When HTTP/2.0 is used by the provider, the connection is refused and dropped causing that video packet to not be received.

This being a major upgrade will be applied to a new release number, instead of a patch upgrade. Once fully implemented, the requests library should not be required and the new HTTPX library will be needed.

**Comment by rocky4546** [comment]
Adding parallel processing of video packets to reduce 404 and timeout errors.  Looks like providers will have a sweet spot for the number of parallel pulls at one time.

**Comment by rocky4546** [comment]
RC04 is not bad.  It has lots of logging and the values are hard coded right now, but daddylive seems to be running much better.

**Comment by Ousret** [comment]
Hello there,

Sorry to barge in,
There's an alternative you may be interested in. https://github.com/jawah/niquests

This is a drop-in-worthy replacement for Requests that ships with modern capabilities and allows you a painless transition.
I can answer any concerns you may have.

**Comment by rocky4546** [comment]
RC08 will be the last version for the httpx updates.  requests will be fully removed at this point. Additional enhancements to 0.9.14 to follow.  Recommend staying with RC08 until all enhancements are complete, but your choice.
