### ISSUE TITLE
[Feature Request] arm64/armv7 docker/ghcr build

### ISSUE THREAD

**Issue by successtheman** [cabernetwork/cabernet#117]
Would it be possible to edit the ghcr.io docker build to add arm64/armv7 support (for raspberry pi)? I have been using this build by eblabs which has arm support https://hub.docker.com/r/eblabs/cabernet/tags for a while now, and I think I may be having issues related to using an outdated docker image (about a year old now). 

I would try to edit the image myself to add arm64/armv7 support but I have no idea where to begin

**Comment by rocky4546** [comment]
Interesting. I don't believe the docker file is machine dependent.  On top of that, you really don't use the ghcr.io file since you should be mounting a volume with the entire Cabernet source in it as stated in the instructions.  So... I think you are "barking up the wrong tree", but I am not in any way an expert on docker.

**Comment by successtheman** [comment]
Correct as the instructions stated I mount the volume with Cabernet source.

When using the ghcr.io image, there seems to be some amount of lag in terms of loading streams and such, I am going to some more testing today to see if maybe it was a fluke when I tried before.

**Comment by successtheman** [comment]
After testing, I can confirm that there is definitely some lag when trying to use the image on RPI4 (arm64) and this is due to it relying on qemu-user-static to emulate amd64 on arm64, so it seems the docker image is architecture dependent after all. I uninstalled qemu-user-static and the image doesn't start anymore on the rpi so that's how I confirmed it. With that said however, you may be right and the image may not be reliant on the docker image itself just the source mounted into the docker container.

**Comment by rocky4546** [comment]
The source is machine independent; however, it does need python3 and ffmpeg binaries to run.  These are provided externally by docker and should be associated with the arch you are using.  The configuration settings will point to the ffmpeg binaries folder or assume it is picked up by the PATH env variable. See Dockerfile_tvh_crypt.alpine for more information on the installs.

**Comment by successtheman** [comment]
Thanks for pointing me in the right direction, I also found something called dedockify which allowed me to somewhat reverse engineer the eblabs image so I will probably end up using a combination of both of them. I just need to figure out how to specify the architecture in the image itself

**Comment by rocky4546** [comment]
My yml file looks a lot different.
https://github.com/cabernetwork/cabernet/blob/master/.github/workflows/docker-image.yml
Someone else created it so I am no docker expert.  It generally works.

**Comment by successtheman** [comment]
> GitlabCI and GitHub use different syntax, it's better to follow the examples/guides above.
> 
> Maybe ill try to create it, and create a PR

This is probably the best option, since Rocky and I are far less experienced with docker (and ARM specifically in this instance). I'm gonna look around and see if I can learn some stuff over the next few days and then maybe I'll be able to help you improve it after you submit the PR.

**Comment by rocky4546** [comment]
cryptography is just a pip install

**Comment by cookieisland** [comment]
> cryptography is just a pip install

In most Linux distributions it is a simple pip install. But Alpine is different and 'pip install' will fail.  That is why the slim-buster dockerfile does a pip install and alpine ends up with the long build to get it installed.

**Comment by successtheman** [comment]
Looks like you made some progress with it today, also I do wonder about those warnings for node12 and such honestly, I got them for some other docker images I was testing in the past

**Comment by successtheman** [comment]
@Generator fyi, you can self host workflow builders on a remote server to bypass github build limits for testing,
I have used this one for another test at some point https://hub.docker.com/r/myoung34/github-runner

**Comment by rocky4546** [comment]
There are quite a few errors in the PR and will need to be fixed before it can be pushed.

**Comment by successtheman** [comment]
@rocky4546 @Generator any update on this? I see the pull request is still sitting there

**Comment by successtheman** [comment]
> I have more changes, but still needs testing. Additional container options for IP, auto-add plugins and more. I'll make a new PR when it's done.

Sounds great! looking forward to testing it

**Comment by rocky4546** [comment]
Thank you Generator for the work so far.  I have pushed the changes into the dev branch and it did build into ghcr.io/cabernetwork/cabernet:dev. Interesting that the "latest" still pulls the master branch, but that is a good thing.
Need to do some testing to see if there are any impacts to the app.  The dev branch does seem to have updated correctly for testing.

**Comment by rocky4546** [comment]
I made some minor tweaks to the docker files.  Tested on both Ubuntu and windows.  All worked very well.  Only issue, not sure about, is when we have an upgrade for Cabernet that also requires an upgrade to the plugins.  Cabernet currently does not handle this well when you try to upgrade Cabernet separately from the plugin upgrade.  Still thinking about it.

**Comment by rocky4546** [comment]
Auto-install plugins on restart sound like a winner.  I will look into it and have it part of this release.  Also, found a bug for non-docker versions during the cabernet upgrade.  Will have that update today.

**Comment by rocky4546** [comment]
FYI... Not sure what is causing it, but the number of Docker downloads per month is 246,000.  The number of downloads for the releases is under 500. It looks like some kind of upgrade check is running a ton and looking like a download.  It really should only be running once a day.  As we get more users, we could reach some kind of GitHub limit caused by users setup of their docker upgrades.

**Comment by rocky4546** [comment]
Plan for docker upgrading the version of Cabernet is to:
1) Detect that the version has changed from the previous start and run the patch upgrade on the ini and db files
2) If there was a version change to Cabernet, also check for plugins to upgrade.  If the upgrade is not compatible with the current version, it will abort the upgrade of that plugin
3) If Cabernet is upgraded by Cabernet, then the previous version value will be updated so that the version detection of a change will not occur

This should also work when people go in and manually do a source overwrite.

**Comment by successtheman** [comment]
Could my issue I have recently encountered here be related to the changes for ARM compatibility?

https://github.com/cabernetwork/cabernet/issues/134
