### ISSUE TITLE
TVHeadend most muxers fail

### ISSUE THREAD

**Issue by oatmealm** [cabernetwork/cabernet#12]
I've got a setup working with Plex. Trying to configure TVHeadnd I've noticed all muxes but few show up FAIL....

```
[plutotv_default]
label = PlutoTV Instance
enabled = True
player-enable_url_filter = True
player-enable_pts_filter = True
channel-import_groups = True
player-stream_type = m3u8redirect
channel-group_name = plutotv

[loggers]
keys = root

[logger_root]
level = DEBUG
handlers = loghandler

[handlers]
keys = loghandler, filehandler

[formatters]
keys = extend,simple

[handler_filehandler]
enabled = False
level = INFO
formatter = extend
class = lib.common.log_handlers.MPRotatingFileHandler
args = (os.getenv('LOGS_DIR','data/logs')+'/cabernet.log', 'a', 10000000, 10)

[handler_loghandler]
enabled = True
class = StreamHandler
formatter = extend
args = (sys.stdout,)

[formatter_extend]
format = %(asctime)s-%(levelname)s:%(module)s %(message)s

[formatter_simple]
format = %(levelname)s:%(module)s %(message)s

[main]
uuid = 81842688-AA85-11EC-924E-00E04C68499A

[hdhomerun]
hdhr_id = 1050A28A

[m3u]
enabled = True

[ustvgo]
enabled = False

[xumo]
enabled = False

[plutotv]
enabled = True

[display]
theme = appletv

```

**Comment by rocky4546** [comment]
I believe you are referencing PlutoTV.  In your configuration, you have it set to m3u8redirect.  This means PlutoTV's m3u8 url is directly sent to TVH and it is up to TVH to negotiate the stream.  So, Cabernet is not involved in the stream and the URL provided is from PlutoTV.

Almost none of the instance setting will matter regarding stream manipulation while in this mode (m3u8redirect).  I normally use internalproxy with PTS/DTS Resync and URL Filtering enabled .  Only issue is when scanning the channels in TVH, TVH will fail if the channel is currently streaming an ad.  What I do is run the scan, then rescan any failed channels until all are working.  If you turn off URL Filtering, I believe you will not have the issue for scanning during ads.

**Comment by rocky4546** [comment]
working as expected.
