### ISSUE TITLE
Add password authentication & https support for web ui config access

### ISSUE THREAD

**Issue by successtheman** [cabernetwork/cabernet#122]
I could be mistaken but it appears there is no way to set a password for the web UI at the moment and there is no native https support (though the password is more concerning to me). This would be a welcomed addition to the software to prevent any unauthorized modifications and such forth

**Comment by rocky4546** [comment]
not a requirement

**Comment by successtheman** [comment]
Why not even consider adding basic http auth without https support for the web ui?
