### ISSUE TITLE
How to input, edit m3u files, use PlutoTV, use TV-grab files ?

### ISSUE THREAD

**Issue by siliconhippy** [cabernetwork/cabernet#125]
Just finished installing Cabernet in a Linode Ubuntu 22.04 US Newark, NJ instance.
Can access UI at :6077. 
Restarted instance several times, systemd systemctl working. Schedule restarts from the UI also done.

All plugins, per the Plugins menu, are installed. Also manually added the Pluto TV config in data/config.ini file, per github Readme.

I would like to use VLC client as test, then Jellyfin/Kodi.

1. Do I need to install tv_grab* files from github if I am not using TVH?

2. Home > Tuner Status menu has no entries. All blank.
Same for Stream/EPG Providers.

4. How do I input or edit my own m3u playlist? TheChannel  Editor just says, Select Tab to Edit ...how ?

5. How do I stream Pluto TV or other to VLC ? I tried 'http://ip address:6077/PlutoTV/channels.m3u' but VLC doesn't stream it.

**Comment by rocky4546** [comment]
1. No, they are only for TVH
2. Normal when not running a stream
3. Use the M3U Plugin.  Add instance to config.ini, restart Cabernet and then configure M3U instance.
4. Use the links page.  Click on channels.m3u and load that file into VLC.  You can also make the browser auto run .m3u files to VLC.

**Comment by siliconhippy** [comment]
OK...

1. Added below to data/config.ini and rebooted my Linode Carbernet instance, also restarted from the Sceduled Tasks:

--------
[plutotv_default]
label = PlutoTV Instance

[m3u_default]
label = M3U Instance

[daddylive_default]
label = DaddyLive Instance

[xumo_default]
label = XUMO Instance

[tvguide_default]
label = TVGuide Instance
------

2. The Home >Tuner Status menu is still blank. 
How do I configure M3U and other instances? Checked all menus as  above- no indication.

3. Clicked on both Links > green /channels.m3u and /playlist M3U. Both download on PC as blank lists. except for #EXTM3U at top !
Channel Editor still shows a pink icon "Select Tab To Edit" but clicking on it does nothing.

Also, /cabernet/data/logs/cabernet.log is blank.

**Comment by rocky4546** [comment]
You have a choice.  Either have nothing in the lists or install a plugin, your choice.  It is up to you.

**Comment by siliconhippy** [comment]
I don't understand.

Are you saying I can only configure one plugin at a time in /data/config.ini, since the plugins menu says all plugins are installed already ?

What does "nothing in the lists" mean?

**Comment by rocky4546** [comment]
The obvious solution has been provided to user since user has yet to install any plugins.  Issue is closed.

**Comment by siliconhippy** [comment]
?
How do I install plugins if the menu says plugins are installed already ; and I am following all instructions for data/config.ini ?
