### ISSUE TITLE
Removing Instance Name from Group Name

### ISSUE THREAD

**Issue by privatesam** [cabernetwork/cabernet#145]
Is there any way to stop the instance name being added to the begnning of the group name?  For example if I specify a group title to a channel in the channel editor fro daddylive like adding 'Sport' to Fox Sport it ends up showing in the resulting m3u liek this: 'Daddylive | Sport' - I wasnt it to be just 'Sport'.

Thanks ahead of time.

**Comment by rocky4546** [comment]
Nope
