### ISSUE TITLE
Daddylive not working, streams returning garbage data

### ISSUE THREAD

**Issue by subby2006** [cabernetwork/cabernet#146]
The stream feed from any of the DaddyLive channels doesn't seem to be playable, the streams are returning garbage data. DaddyLive recently changed to encrypting their feed and the key is usually on the top of the m3u8 in the format https://key.onlinehdhls.ru/wmsxx.php?name=<channelid> but I think cabernet is failing to decrypt the streams, resulting in a blank screen when played through VLC. PlutoTV and everything else is working fine and there are no errors in the docker log. I'm using the docker setup and the streaming setup is using the internal proxy
![image](https://github.com/cabernetwork/cabernet/assets/65925208/8440a782-0bf0-4a16-a858-4ecd5dd9bacd)

**Comment by rocky4546** [comment]
wrong repo.  Issue already listed in DL, closing as dup

**Comment by subby2006** [comment]
> wrong repo. Issue already listed in DL, closing as dup

mind sharing a link to the repo/issue?
