### ISSUE TITLE
Unable to get daddylive plugin functioning

### ISSUE THREAD

**Issue by Joshbloam** [cabernetwork/cabernet#147]
I have tried all of the available player stream_types available. Anyone else seeing this?? Here is the error message I get when using streamlinkproxy. Any help is appreciated!!

Version: 0.9.15.00-RC01

![image](https://github.com/cabernetwork/cabernet/assets/10256258/0736b027-6787-490a-aad1-0b45bd0dbc3d)

![image](https://github.com/cabernetwork/cabernet/assets/10256258/7fe11f52-89e7-4ade-af36-a987de3959ed)

**Comment by benjaminfrombe** [comment]
Same issue here ... since a couple of days

**Comment by rocky4546** [comment]
wrong repo.  duplicate already exists in plugin. closing
