### ISSUE TITLE
Jellyfin Channel Maping

### ISSUE THREAD

**Issue by noideaman** [cabernetwork/cabernet#154]
I am using default settings in docker and the plutovt and xumo plugins installed.

I added the ip of the host running cabernet as a hdhomerun device in jellyfin. the channels populated
i then added the xmltv url but it will not auto map.

Is there a setting i am missing because i don't want to manual map over 700 channels

**Comment by rocky4546** [comment]
See #78, it has all the info to make it work.  I recommend looking for  "Use Channel # for Channel ID" in the issue for details.  Also, you can look at the tool tip on the variable as well.

**Comment by noideaman** [comment]
i had those settings, idk why they where failing, i got it fixed by removing the data from the container and rebuilding it, and restarting jellyfin every time i updated jellyfin. 

Now i am just trying to figure out how to make pluto tv not fail when it moves to commercials.
the pluto tv streams do 1 of 2 things. either it stays on the last frame and when the commercials are over it picks back up. or it just fails to continue and i have to restart the stream.

**Comment by noideaman** [comment]
oh and if the stream crashes out it shows this and i cant re-load the stream untill the client that failed restarts
![image](https://github.com/user-attachments/assets/4125c539-6dd3-4bad-9c66-c895d21ae47a)

**Comment by rocky4546** [comment]
This is a separate issue, please write an issue under plutotv plugin.
