### ISSUE TITLE
Only seeing 2 x TV tuners in plex after  setting up Cabernet docker, and installing Daddylive addon. 



### ISSUE THREAD

**Issue by riyaaz2016** [cabernetwork/cabernet#156]
Only seeing 2 x TV tuners in plex after  setting up Cabernet docker, and installing Daddylive addon. 

Is there a limit on how many tuners can use and add to Plex dvr, currently have 2 that comes come via Daddylive, yet default TV tuner count in Cabernet app is set to 10?

 I am running cabernet 0.9.15.00-RC01 and daddylive addon v0.1.31 which is latest one. 

Any idea how this works and to add more in plex?

**Comment by rocky4546** [comment]
Number of tuners for Plex is provided by Cabernet.  Take the URL you provided to plex and add "/discover.json"  This provides the tuner count to plex.  I ran a test right now and plex is definitely providing more than 2 tuners.  You should look through the setup guide #78 it may provide info you need to solve your plex issue.

**Comment by riyaaz2016** [comment]
Awesome stuff, thank you.

Will check this out 😁

**Comment by riyaaz2016** [comment]
What's link to that setup guide for #78?
