### ISSUE TITLE
Stirr, Newson and other plugins

### ISSUE THREAD

**Issue by Protektor-Desura** [cabernetwork/cabernet#16]
I thought I would point out some Python code that you might be able to use to add internal support for Stirr TV.

https://stirr.com/
https://github.com/fHDHR/fHDHR_plugin_origin_STIRR

Here is on for NewsOn to get news and local news for some cities.

https://www.newson.us/
https://github.com/fHDHR/fHDHR_plugin_origin_NewsOn

Here are some scripts for pulling Zap2It guide details.

https://github.com/fHDHR/fHDHR_plugin_epg_zap2it
https://github.com/arantius/zap2xml-py
https://github.com/jbreen60030/plex.zap2it.xmltv
https://github.com/edit4ever/script.module.zap2epg

**Comment by rocky4546** [comment]
There are always plenty of new providers coming out of the woodwork. The plan is to manage only a few plugins from the Cabernet repo and allow you and others to create new plugins as you see fit.  Not quite there yet with external repo links, but it is comint in the next few months. Cabernet will not be supporting these as plugins.  Some already can use the m3u plugin, if not, then the expectation is to have people create new plugins.
