### ISSUE TITLE
Portainer YML

### ISSUE THREAD

**Issue by Elsys656** [cabernetwork/cabernet#163]
Generic portainer YML for static ip setup, in case your hosting your cabernet from the same box your streaming it with. you can adjust the subnet if needed to gain other ip addresses but with docker it should route everything the same. Compatible with portainer community and business I think.

```
version: '2.4'
services:
    cabernet:
        container_name: cabernet
        image: ghcr.io/cabernetwork/cabernet:latest
        ports:
          - "6077:6077"    # Web Interface Port
          - "5004:5004"    # Port used to stream
        restart: unless-stopped
        networks:
          cnrelay:
            ipv4_address: 10.5.0.5
        volumes:
          - /storage/.docker/data-root/volumes/data/_data:/app/data                # App data (Optional)
          - /storage/.docker/data-root/volumes/plugins/_data:/app/plugins_ext  # Plugins Data (Optional)
          - /storage/.docker/data-root/volumes/secret/_data:/app/.cabernet        # Ecryption key data (Optional)
networks:
  cnrelay:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

**Comment by Elsys656** [comment]
just thought id put this here to help people doing the setup this way,

**Comment by Elsys656** [comment]
```
version: '2.4'
services:
    cabernet:
        container_name: cabernet
        image: ghcr.io/cabernetwork/cabernet:latest
        ports:
          - "6077:6077"    # Web Interface Port
          - "5004:5004"    # Port used to stream
        restart: unless-stopped
        networks:
          cnrelay:
            ipv4_address: 10.5.0.5
        volumes:
          - /storage/.docker/data-root/volumes/data/_data:/app/data                # App data (Optional)
          - /storage/.docker/data-root/volumes/plugins/_data:/app/plugins_ext  # Plugins Data (Optional)
          - /storage/.docker/data-root/volumes/secret/_data:/app/.cabernet        # Ecryption key data (Optional)
networks:
  cnrelay:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

**Comment by Elsys656** [comment]
it helps avoid tvheadend or jellyfin or nextpvr channel refresh issues after a restart, additionally you could add into your next version a localhost support, wherin the ip exposed in the internal proxy is http://0.0.0.0:5004/stream/guid, or localhost because in the file it takes whatever ip the virtual machine sees and hardcodes that rather than explicitly using loopback.

**Comment by Toei79** [comment]
how get pluto from other country instead my ip? lol i asked other thread just see a long shot

i get  pluto playlist from other country running but using m3u plugin nothing plays.

**Comment by Elsys656** [comment]
Configure your openvpn setup to allow internal ip address, in config file whatever portioner assigned as a mask that way you have properly working guide info and a secure connection. 10.5.0.5, you can see at least in the Kodi addon for example that it already whitelists internal ip addresses for most home network defaults 192.168.x.x,

line should look like !https://192.168 !http://192.168 !https://10.5 !http://10.5
there's a line there that shows you the format just add whatever you assigned your static internal to it.
Now the relay will still be encrypted by the physical NIC for external ip addresses and should pull information based on your vpn location of choice instead of having the pluto internal proxy block guide information.
