### ISSUE TITLE
Current back ups not showing in the UI

### ISSUE THREAD

**Issue by MartinR577** [cabernetwork/cabernet#165]
in the UI on the Cata management under Current Backups it only shows 2 from 4/25/2024
 04/25/2023, 12:16 PM/app/data/backups/CarbernetBackup_20230425_1216 
04/25/2023, 11:47 AM/app/data/backups/CarbernetBackup_20230425_1147

but in the folder i have many more. it seems the UI is filtering for "CarbernetBackup_<Date_Time>". (note the additional R in "Carbernet". The actual new backups is in the naming format  "CabernetBackup_<<cabernetrelease>_Date_Time>. these are ignored in the program.

**Comment by rocky4546** [comment]
Fixed regex for backup display. See RC02.
