### ISSUE TITLE
upgrading to 0.9.15.00-RC02 on docker

### ISSUE THREAD

**Issue by devkind39** [cabernetwork/cabernet#167]
Hello everyone. I currently have 0.9.15.00-RC01 running in docker in an Ubuntu Server. When I try to click on the upgrade button on the webUI to upgrade to  0.9.15.00-RC02, I receive the following error:

"Starting upgrade...
Checking current install area for expected files...
#### Extra file(s) found in install directory, aborting upgrade. FILE: Do_Not_Upgrade_from_WEBUI_on_Docker
Upgrade aborted"

Any suggestions for alternate ways of upgrading?

**Comment by rocky4546** [comment]
use docker for upgrades, not the ui

**Comment by devkind39** [comment]
Got it! Thanks. It worked.
