### ISSUE TITLE
Cant find way to add m3u after installing M/U plugin

### ISSUE THREAD

**Issue by Hula1267** [cabernetwork/cabernet#174]
Where can I add m3u's?

![image](https://github.com/user-attachments/assets/4b896ed3-a4db-4a47-93c8-1780d387a4ef)

**Comment by ovargasp** [comment]
as @rocky4546 mentioned in another issue: Try following the issue https://github.com/cabernetwork/cabernet/issues/78,  Start with that and then see where it goes. Everything is pretty clear there...
