### ISSUE TITLE
Use channel # as channel ID causes mismatch between .m3u and .xml

### ISSUE THREAD

**Issue by proxmoxdebbie** [cabernetwork/cabernet#178]
Is it possible to update the channels.m3u channel ID to match the xmltv.xml Channel ID when using Client>EPG>Use Channel # as Channel ID?  Possibly also the tvg-id field should be updated.  Currently the .m3u appears to be pulling data from the metadata column for use as the channel ID and tvg-id.  I am not sure if this or the multiple display names is causing mapping issues when importing M3U+xml into jellyfin.

https://github.com/jellyfin/jellyfin/pull/6485

>Changes
>Sets the ExtInf display name to have a higher precedence than the tvg-name attribute for channel names.
>
>Usually namInExtInf is a more descriptive and human readable name if both it and tvg-name are available. tvg-name is more >likely to be an internal identifier such as just the channel number with a prefix in my provider's case.

https://github.com/jellyfin/jellyfin/pull/10323

> Fixes issue https://github.com/jellyfin/jellyfin/issues/6527
>
>Removed the the condition that checks if a channel has an id (tv guide id), it uses it as an unique id with md5 hash.
>This was kinda wrong since :
>
>We can have multiple channels lines in a m3u which uses same tv guide (SD and HD version of same broadcast for example)
>The behavior of the code was not explicit, all the code flow kept all channels until we write them down to the database , then since they have same unique generated id , the first channel is written to the db and then the following channel with same id overwrites it.
>
>I Thought of adding a checkbox to keep old behavior at m3u tuner level but I am quite sure the condition/old behavior is not needed and was wrong/not intended.

M3U
>#EXTM3U
>#EXTINF:-1 channelID='501' tvg-num='2' tvg-chno='2' tvg-name='18+ (Player-01)' tvg-id='501' group-title='DaddyLive',18+ (Player-01)
>http://x.x.x.x:5004/DaddyLive/auto/v2

Default XML (format modified by me to display properly on github)
>channel id="501"
>display-name 2 18+ (Player-01) /display-name
>display-name 18+ (Player-01) /display-name
>display-name 501 /display-name
>display-name 2 501 /display-name
>/channel

Channel# as Channel ID XML, causing M3U/XML mismatch (format modified by me to display properly on github)
>channel id="2"
>display-name 2 18+ (Player-01) /display-name
>display-name 18+ (Player-01) /display-name
>display-name 501 /display-name
>display-name 2 501 /display-name
>/channel>

Metadata from channel editor where M3U appears to get Channel #
>HD Live 501 501
>['P1P2']

**Comment by rocky4546** [comment]
Same issue as #168.
Try following the issue https://github.com/cabernetwork/cabernet/issues/78, the info provided indicates you did not follow the beginners guide. Start with that and then see where it goes. Most of your issues are discussed in that issue.

**Comment by proxmoxdebbie** [comment]
> Same issue as #168. Try following the issue #78, the info provided indicates you did not follow the beginners guide. Start with that and then see where it goes. Most of your issues are discussed in that issue.

Could you please re-read my post and give a direct answer to the question posed in the first line?  With all due respect your assumption that I have not read and followed that guide is incorrect.  The thread you gestured towards seems to indicate you are using emby and not Jellyfin, there is no ability to "edit channels" in jellyfin 10.10.1.   as referenced in jellyfin#10323 above.

Try spinning up this docker stack, adding the plex playlist to cabernet via the M3U plugin, renumbering the channels for Diddylive, Xumo and Plex and having the guide info and channel numbering import into jellyfin 10.10.1.  

>  cabernet:
    image: ghcr.io/cabernetwork/cabernet:latest
    container_name: cabernet
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DATA:?err}/cabernet/data:/app/data
      - ${FOLDER_FOR_DATA:?err}/cabernet/plugins_ext:/app/plugins_ext
      - ${FOLDER_FOR_DATA:?err}/cabernet/secrets:/app/.cabernet
    ports:
      - "${WEBUI_PORT_CABERNET:?err}:6077"
      - "${CABERNET_HDHOMERUN_PORT:?err}:65001"
      - "${CABERNET_SSDP_PORT:?err}:1900"
      - "${CABERNET_STREAM_PORT:?err}:5004"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    networks:
      - ${MEDIA_NETWORK_NAME:?err}
  free-iptv-channels:
    image: dtankdemp/free-iptv-channels:latest
    container_name: iptvchannels
    restart: unless-stopped
    networks:
      - ${MEDIA_NETWORK_NAME:?err}
    ports:
       - "${WEBUI_PORT_IPTV_CHANNELS:?err}:4242"
   jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    devices:  # Enable Configurations for GPU Hardware Rendering
      - /dev/dri/renderD128:/dev/dri/renderD128
      #- /dev/dri/card0:/dev/dri/card0
    volumes:
      - ${FOLDER_FOR_DATA:?err}/jellyfin:/config
      #- ${FOLDER_FOR_MEDIA:?err}:/data
    ports:
      - "${WEBUI_PORT_JELLYFIN:?err}:8096"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    networks:
      - ${MEDIA_NETWORK_NAME:?err}

**Comment by proxmoxdebbie** [comment]
After doing some more testing it seems channel id mismatch between .m3u and .xml is mostly irrelevant, the problem appears to be the multiple display names in the xmltv.xml file. 

Jellyfin seems to parse the .xml best when the .xml has a single display-name attribute that contains the tvg-name. When there are collisions between display names for a single channel or display-name values accross multiple channels jellyfin will never import the guide data automatically.

>[loggers]
keys = root
l
[logger_root]
level = TRACE
handlers = loghandler
l
[handlers]
keys = loghandler, filehandler
l
[formatters]
keys = extend,simple
l
[handler_filehandler]
enabled = False
level = INFO
formatter = extend
class = lib.common.log_handlers.MPRotatingFileHandler
args = (os.getenv('LOGS_DIR','data/logs')+'/cabernet.log', 'a', 10000000, 10)
l
[handler_loghandler]
enabled = True
level = WARNING
class = StreamHandler
formatter = extend
args = (sys.stdout,)
l
[formatter_extend]
format = %(asctime)s-%(levelname)s:%(module)s %(message)s
l
[formatter_simple]
format = %(levelname)s:%(module)s %(message)s
l
[main]
uuid = redacted
maintenance_mode = False
l
[hdhomerun]
hdhr_id = redacted
l
[tvguide]
enabled = True
l
[daddylive]
hdhr_id = redacted
enabled = True
epg-plugin = ALL
l
[daddylive_default]
label = DaddyLive Instance
enabled = True
l
[tvguide_default]
label = TVGuide Instance
enabled = True
l
[web]
plex_accessible_ip = redacted
l
[display]
display_level = 3-Advanced

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = False
epg_use_channel_number = False
epg_add_plugin_to_channel_id = False
l
NBC is mapped to channel 53 and Arena Sport to channel 135 no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="135"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="53"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = True
epg_use_channel_number = False
epg_add_plugin_to_channel_id = False
l
NBC is mapped to channel 418 and Arena Sport to channel 53, no guide info imported. List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="135"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="53"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = False
epg_use_channel_number = True
epg_add_plugin_to_channel_id = False
l
NBC and Arena Sport are not mapped to a number, no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="53"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="418"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = False
epg_use_channel_number = False
epg_add_plugin_to_channel_id = True
l
NBC mapped to 53 ArenaSport to 135, no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="DaddyLive-135"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="DaddyLive-53"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = False
epg_use_channel_number = True
epg_add_plugin_to_channel_id = True
l
NBC and Arena Sport are not mapped to a number, no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="DaddyLive-53"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="DaddyLive-418"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = True
epg_use_channel_number = True
epg_add_plugin_to_channel_id = False
l
NBC is mapped to channel 418 and Arena Sport to channel 53 no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="53"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="418"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = True
epg_use_channel_number = False
epg_add_plugin_to_channel_id = True
l
NBC is mapped to channel 418 and Arena Sport to channel 53 no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="DaddyLive-135"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="DaddyLive-53"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------
>[epg]
epg_channel_number = True
epg_use_channel_number = True
epg_add_plugin_to_channel_id = True
l
NBC is mapped to channel 418 and Arena Sport to channel 53 no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is empty
l
channel id="DaddyLive-53"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name135/display-name
display-name53 135/display-name
/channel
channel id="DaddyLive-418"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameWXIA/display-name
display-name418 WXIA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel

--------------------------------------------------------------------------------------------------------

>Using threadfin to sanitize the .xml and remap NBC to channel 418 and Arena Sports to channel 53, they were not automatically mapped.
Channels are correctly mapped by jellyfin and guide data is present.  
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is populated with the correct entries
l
[epg]
epg_channel_number = False
epg_use_channel_number = False
epg_add_plugin_to_channel_id = False
l
Threadfin .xml output
l
channel id="53"
display-nameArena Sport 2 Premium/display-name
icon src=""/
livetrue/live
activetrue/active
/channel
channel id="418"
display-nameNBC USA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
livetrue/live
activetrue/active
/channel

--------------------------------------------------------------------------------------------------------

>Using a 2nd instance of Cabernet on a different physical machine with only the M3U plugin and the m3u/xml output of threadfin used as an input:
NBC and Arena Sport are not mapped to a number, no guide info imported.
List of channels which may be mapped in http://0.0.0.0:8096/web/#/dashboard/livetv is populated with numbered entries and manually mapping channels will populate the guide with the correct guide info, channels are not numbered. epg_channel_number = True and epg_use_channel_number = True in the 2nd instance have no effect.
l
1st cabernet instance
[epg]
epg_channel_number = False
epg_use_channel_number = False
epg_add_plugin_to_channel_id = False
l
2nd cabernet instance
[epg]
epg_channel_number = False
epg_use_channel_number = False
epg_add_plugin_to_channel_id = False
l
channel id="53"
display-name53 Arena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-nameArena Sport 2 Premium/display-name
display-name53 Arena Sport 2 Premium/display-name
/channel
channel id="418"
display-name418 NBC USA/display-name
display-nameNBC USA/display-name
display-nameNBC USA/display-name
display-name418 NBC USA/display-name
icon src="https://www.tvguide.com/a/img/catalog/provider/1/4/1-4101478725.png"/
/channel
