### ISSUE TITLE
Some channels not working and epg not showing?

### ISSUE THREAD

**Issue by ls-milkyway** [cabernetwork/cabernet#180]
Plugin: Daddylive
Channel:
Star Sports Hindi IN

Error:
2024-11-28 23:41:11,992-WARNING:__init__ INVALID m3u format: #EXTM3U missing https://XXXXXXX.mizhls.xx/lb/premium268/index.m3u8

EPG:
TVGuide plugin.
File:
xmltv.xml does not show any program??

**Comment by rocky4546** [comment]
Channels go down at times.  If you want, you can request DL to reset the channel and that normally get it back up.  As for the EPG, if you do not have it enabled, it won't exist.  Recommend going through #78 which has this info as well.

**Comment by ls-milkyway** [comment]
> Channels go down at times. If you want, you can request DL to reset the channel and that normally get it back up. As for the EPG, if you do not have it enabled, it won't exist. Recommend going through #78 which has this info as well.

After reading #78 I was able to populate epg on some channels (I think that's normal as all channels are not included in tvguide).

What do you mean by request DL to reset the channel? Can you elaborate it?

Which time zone should I select for all the programs populated on the EPG to be listed in [IST](https://www.timeanddate.com/time/zones/ist)

FYI, I am posting my config.ini

[loggers]
keys = root

[logger_root]
level = TRACE
handlers = loghandler

[handlers]
keys = loghandler, filehandler

[formatters]
keys = extend,simple

[handler_filehandler]
enabled = False
level = INFO
formatter = extend
class = lib.common.log_handlers.MPRotatingFileHandler
args = (os.getenv('LOGS_DIR','data/logs')+'/cabernet.log', 'a', 10000000, 10)

[handler_loghandler]
enabled = True
level = WARNING
class = StreamHandler
formatter = extend
args = (sys.stdout,)

[formatter_extend]
format = %(asctime)s-%(levelname)s:%(module)s %(message)s

[formatter_simple]
format = %(levelname)s:%(module)s %(message)s

[main]
uuid = C6583D84-8FAA-11EF-A79B-5CE42A16BCE0
maintenance_mode = False
use_encryption = True

[hdhomerun]
hdhr_id = 105A27CF

[display]
display_level = 3-Advanced

[paths]
ffmpeg_path = E:\Apps\Streamlink-6-10-0-1-py312\ffmpeg\ffmpeg.exe
ffprobe_path = E:\Apps\Streamlink-6-10-0-1-py312\ffmpeg\ffprobe.exe
streamlink_path = E:\Apps\Streamlink-6-10-0-1-py312\bin\streamlink.exe

[web]
plex_accessible_port = XXXX
web_admin_port = XXXX

[tvguide]
enabled = True

[daddylive]
hdhr_id = 105C787D
enabled = True
epg-plugin = ALL

[daddylive_default]
label = DaddyLive Instance
enabled = True

[tvguide_default]
label = TVGuide Instance
enabled = True

[channels]
thumbnail_size = Small(48)

[epg]
genre = normal
epg_channel_number = True
epg_use_channel_number = True
description = normal
epg_prettyprint = True

Thanks.
