### ISSUE TITLE
issue with [web] section of config.ini file

### ISSUE THREAD

**Issue by devkind39** [cabernetwork/cabernet#183]
I'm having problems with the ip settings under the [web] section of the config.ini file. I've checked Issue #78 but this topic is not explicitly addressed.

I'm running cabernet in a docker container on a remote system running ubuntu server (This is set up outside of my LAN).

Apparently there are at least 3 potential ip settings in that section: local_ip, plex_accessible_ip and plex_docker_ip

The instructions say to set plex_docker_ip to my computer's IP. However, when I do this, the container dies a sad death and needs to be killed and restarted. It works fine if plex_docker_ip is set to something like 172.17.0.3 or such. However, the channels.m3u file would need to be updated manually with the WAN IP of my remote ubuntu server. 

Any suggestions for how to set these 3 IP settings under the [web] section of the config.ini file? Thank you in advance.

**Comment by ovargasp** [comment]
I'm not quite sure about your interpretation of "plex_docker_ip to my computer's IP", I've a server running a docker container (same network) and what I did was to set plex_docker_ip to the server ip address, to me the idea is that the playlist has to have the correct IP for the client to connect to the straming port... but yours is in a different network so is hard to tell what do you want your clients to do exactly, just get the playlist, get the streams out of the server... if you'll use a VPN, etc...

**Comment by rocky4546** [comment]
overgasp is correct.  plex_docker_ip only makes changes to the m3u file output, so any crashing has nothing to do with that variable.  local_ip normally should be 0.0.0.0 (which means connect with any ip address available). If you are using docker, then leave this alone and set the plex_docker_ip variable.

**Comment by devkind39** [comment]
You were right. It appears the container was crashing due to running out of usable system memory. I terminated a few other processes that were taking up memory on the server. And all is fine now. Thanks.
