### ISSUE TITLE
How to backup channels, settings and restore them in a fresh python (environment) install.

### ISSUE THREAD

**Issue by ls-milkyway** [cabernetwork/cabernet#184]
Since Channels are carefully selected with changes in names and groups, how can I backup and restore them in a fresh python install ...will channels.db and some settings in config.ini be sufficient?

**Comment by rocky4546** [comment]
Have you looked at the backups in Cabernet.  They are in the Data Management section and occur automatically once a week by default per the scheduled task.  The backups are found in the data/backups folder is you want to copy them somewhere.

**Comment by ls-milkyway** [comment]
> Have you looked at the backups in Cabernet. They are in the Data Management section and occur automatically once a week by default per the scheduled task. The backups are found in the data/backups folder if you want to copy them somewhere.

Yes I have, but I am not sure whether it's a complete backup (doing a fresh install is useless in such a case) OR it's only Cabernet's settings backup. Actually twice my daddylive channel editing button vanished ...and it's PTA to set/remove/add groups,names to channels again and again ...plus I tried to restore the Cabernet by existing backup but it did not work.

Also due recent change in Cabernet's m3u streaming urls most of the channels are dead ..some of them are working in VLC but none of them are working from my TV in local network....maybe it;s a firewall issue.

**Comment by ls-milkyway** [comment]
config.ini and channels.db are sufficient to restore channels ...but one needs to install plugins again.
