### ISSUE TITLE
Cabernet picking VPN adapter's IP address instead of PC IP address.

### ISSUE THREAD

**Issue by ls-milkyway** [cabernetwork/cabernet#186]
This is strange...when I install Cabernet on PC and turn on VPN ...then m3u playlist generated shows entries with VPN adapter's IP instead of PC's IP ... hence TV in my home network refuses to play channels.

For example play list generated has:

`#EXTINF:-1 channelID='923' tvg-num='43' tvg-chno='43' tvg-name='Altitude Sports (Caber)' tvg-id='923' group-title='DaddyLive|Sports',43 Altitude Sports (Caber)
http://xx.xxx.0.69:9100/DaddyLive/auto/v43`

where xx.xxx.0.69 is the IP of my VPN Adapter ...this plays well on VLC installed on my PC but not on the TV in my home network.

And if I change IP say:

`#EXTINF:-1 channelID='923' tvg-num='43' tvg-chno='43' tvg-name='Altitude Sports (Caber)' tvg-id='923' group-title='DaddyLive|Sports',43 Altitude Sports (Caber)
http://xxx.xxx.0.50:9100/DaddyLive/auto/v43`

Where xxx.xxx.0.50 is the IP of my wifi adapter on PC ..I am able to play channels on TV even with VPN on ....I can't find any settings in Cabernet to change this; it always generates playlist with VPN adapter's IP?

Also getting warnings using xxx.xxx.0.50:
` InsecureRequestWarning: Unverified HTTPS request is being made to host 'thexxxxy.xo'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings`

Kindly suggest.

**Comment by subby2006** [comment]
Go to clients on the web panel, then set the `plex_docker_ip` to whatever IP address your PC has

**Comment by ls-milkyway** [comment]
> Go to clients on the web panel, then set the `plex_docker_ip` to whatever IP address your PC has

Cabernet is non docker version i.e. it's running on python environment.
