### ISSUE TITLE
Looking for guidance on a particular m3u / EPG

### ISSUE THREAD

**Issue by Aetherinox** [cabernetwork/cabernet#189]
The people at https://github.com/dtankdempse/thetvapp-m3u have released a list of channels, as well as an EPG file.

If I import these directly into Jellyfin, it works. I get the icon for each channel, and the EPG data works.

I wanted to import these into Cabernet because then it allows me to choose which channels I get, but the issue is, as soon as I enable the M3U plugin and add the proper m3u and epg xml url and do a refresh on Jellyfin, all of the channels show up, but without icons, and no guide data.

If I go into Jelly's live channel settings and like "Map channel" for the EPG file hosted by Cabernet, I can manually map every channel, and then it works. But of course, after 2-3 days, all the data changes, and then the channels are unmapped again, and that just becomes a royal pain.

I compared the EPG file data to other services, and the format seems to be proper. The only thing I can think of is that for the one not working, the `tvg-name` is different.

As an example, with DaddyLive, you get:

```
channelID='685' tvg-num='daddy539' tvg-chno='daddy539' tvg-name='Sky Crime' tvg-id='685'
```

And that's because I've prefixed a number, but with the one I linked above, but with the one I linked above, the names seem to have a lot more special characters in them.

```
channelID='A.and.E.US.-.Eastern.Feed.us' tvg-num='tvapp800' tvg-chno='tvapp800' tvg-name='A&E' tvg-id='A.and.E.US.-.Eastern.Feed.us'
```

I've also tried importing without a prefix number, I've set all settings to default, and let it just import the data with no manipulation. That doesn't work either.

I've opened / compared the m3u and EPG file, and I can match the tvg-name to the correct epg entries, so they're in there. It just doesn't want to automatically map them if I use cabernet.

Any ideas as to the reason? It would be awesome to limit certain channels and not do a straight import.

Here's the m3u part of my config, I've tried it with many settings, including just wiping any custom settings and doing it straight out of box, with no prefix or anything. But if I do the same prefixing to the DaddyLive plugin, works great. Only difference is that's a plugin, this is a m3u import.

```
[m3u]
hdhr_id = 105AEC2E
enabled = True
epg-plugin = ALL

[m3u_default]
label = TheTvApp
enabled = True
channel-m3u_file = https://tvapp.domain.com/playlist
channel-start_ch_num = 800
player-stream_type = m3u8redirect
epg-xmltv_file = https://raw.githubusercontent.com/dtankdempse/thetvapp-m3u/main/guide/epg.xml
channel-m3u_file_type = m3u
epg-xmltv_file_type = xml
channel-group_name = thetvapp
epg-prefix = tvapp
```

the `channel-m3u_file` is the correct domain, just censored it here.

If I compare the m3u file between just a straight import, and using cabernet:

```
## This one is imported directly into Jellyfin -- [ WORKS ]
#EXTINF:-1 tvg-id="A.and.E.US.-.Eastern.Feed.us" tvg-name="A&E" tvg-logo="http://schedulesdirect-api20141201-logos.s3.dualstack.us-east-1.amazonaws.com/stationLogos/s51529_dark_360w_270h.png" group-title="Entertainment",A&E
https://v16.thetvapp.to/hls/AEEast/index.m3u8?token=XXXXXXX==

## This one is imported using Cabernet -- [ DOES NOT WORK ]
#EXTINF:-1 channelID='A.and.E.US.-.Eastern.Feed.us' tvg-num='tvapp800' tvg-chno='tvapp800' tvg-name='A&E' tvg-id='A.and.E.US.-.Eastern.Feed.us' tvg-logo='http://schedulesdirect-api20141201-logos.s3.dualstack.us-east-1.amazonaws.com/stationLogos/s51529_dark_360w_270h.png' group-title='M3U|thetvapp|series',A&E
https://v13.thetvapp.to/hls/AEEast/index.m3u8?token=XXXXXXX==
```

I notice that the Cabernet version has a field `channelID`.

**Comment by rocky4546** [comment]
you will need to provide the m3u file to get help.

**Comment by Aetherinox** [comment]
Oops, sorry. Here is the m3u file being generated by cabernet with the current settings.

Note, I had to re-name the file from `.m3u` to `.txt`. Github doesn't allow .m3u attachments. This m3u file is both DaddyLive and the one I linked above.

[channels.txt](https://github.com/user-attachments/files/18271479/channels.txt)

**Comment by rocky4546** [comment]
OK, I went through the process of adding the m3u plugin and ingesting the m3u file you provided as well as the epg file from the github site.  Then, went to Jellyfin and added the live tv interface.  In the Guide portion of the livetv page, it had all 141 channels listed with the correct channel numbers.  Only about 10 channels did not have guide data.  So, it looks like it works fine.  Also, the channel icons were all present.

Based on the lengthy text you provided, I believe you have not read, comprehended and implemented the Beginners Setup guide which could the the cause of your frustration.

**Comment by Aetherinox** [comment]
Then there has to be something I'm missing here. Because I've read that beginners setup / discussion, at least 3 times. I can find any other m3u and epg source online and it works perfect with the m3u plugin. It's only when I attempt to add the repo I pasted above.

And I've done a complete wipe of the epg / channels, and restarted cabernet dozens of times. 

Yet if I find another m3u source online, and add that to cab, works fine. Zero issues. Icons load, EPG guide works. So there's obviously something here I'm missing.

**Comment by Aetherinox** [comment]
So I've played with this for six hours. 

For some reason, using M3U Tuner in Jellyfin results in solid color boxes, no guide data.

However, if I switch over to HDHomeRun and refresh in Jellyfin, then I can get the icons and guide data to load.

![Nnj7sj1gt1](https://github.com/user-attachments/assets/7b5a9c14-ad14-426b-ac4f-ddf8aae50495).

But I can try other sources with M3U Tuner, and it works fine. And I've gone through that discussion page and checked every aspect. 

And I validated with cabernet that the m3u file is properly there and accessible by Jellyfin.

**Comment by clseibold** [comment]
> Based on the lengthy text you provided, I believe you have not read, comprehended and implemented the Beginners Setup guide which could the the cause of your frustration.

So... where is this so called "Beginners Setup guide"?

**Comment by Aetherinox** [comment]
Yeah, I'd mostly definitely think about some actual docs. That discussion is hard to read through. I had to spend 3 hours diagnosing it. Good app, but the docs are lacking.

I then went here: https://cabernetwork.github.io/documentation/

And that's just a giant template of placeholders.

**Comment by clseibold** [comment]
If rocky4546 doesn't have the time, then someone else could try to create some docs out of that issue and their knowledge of the program and submit a PR to https://github.com/cabernetwork/cabernetwork.github.io . I might consider doing this sometime in the future if someone else doesn't... as soon as I figure out everything with this program, lol.

**Comment by clseibold** [comment]
Just found out that turning on "Channel # in Name" has helped tremendously in getting the channels sorted and auto-mapped correctly by Jellyfin.
