### ISSUE TITLE
Not creating config.ini

### ISSUE THREAD

**Issue by Protektor-Desura** [cabernetwork/cabernet#19]
When you first run the docker it errors out that the config.ini doesn't exist. I had to just create an empty file then it would launch. The app instead of complaining that the config.ini doesn't exist it should just create it.

**Comment by Nostradamus1973** [comment]
Good morning everyone,

I know I'm coming to the party late, but, I'm having a heck of a time trying to get this to run in docker for me. I'm new to docker(and loving it) I'm also running portainer as a front end on Ubuntu 22.10 with a few dockers running.
I used the docker-compose.yml that @Protektor-Desura had written up and I still can't get this working.
Can someone please help me with this?
I JUST found this app yesterday and I had a: "Where have you been all my life???" moment when I saw the absolute genius behind this script. I would love to get this running.

Thank you and have a nice day.

**Comment by rocky4546** [comment]
fixed.  Now creates config.ini
