### ISSUE TITLE
Show picture

### ISSUE THREAD

**Issue by Protektor-Desura** [cabernetwork/cabernet#20]
I notice that a lot of shows have images for what is/the show playing at moment, but not all. Could we get Cabernet to shove in the logo for the channel when there isn't an image for that specific show?

On Jellyfin these images are used in the list of "On Now".

**Comment by rocky4546** [comment]
Info is provided by the TVXML file.  If not provided by the provider, then it would not be available.  Cabernet is not a media server like Plex, Jellyfin or Emby.  If the tvxml file does contain it and it is not provided by cabernet through the epg interface, let me know.
