### ISSUE TITLE
USTVGO M3U Updates

### ISSUE THREAD

**Issue by Protektor-Desura** [cabernetwork/cabernet#25]
I think the USTVGO channels M3U needs to be updated every 2-3 hours. They use a key for each channel, and I notice when chrome-casting the website that every couple of hours watching Fox News I had to refresh the webpage to keep watching.

**Comment by rocky4546** [comment]
My wife has been running Hallmark continuously most of each day without issue.  I do not believe this is an issue in general.

**Comment by rocky4546** [comment]
USTVGO is no more, closing issue
