### ISSUE TITLE
[improvement] Export edited playlist or make them all inactive by default

### ISSUE THREAD

**Issue by oatmealm** [cabernetwork/cabernet#26]
Would it be possible to allow exporting an edited playlist of a particular provider so it can be backed up with the config files? First thing I do is remove all the right-wing media nonsense like Fox, oan etc., but Pluto as well has an unmanageable list of channels, of which one or two are useful to me. 10x.

**Comment by rocky4546** [comment]
The edited playlist should be provided by 
http://ip:6007/channels.m3u
http://ip:6007/provider/channels.m3u
http://ip:6007/provider/instance/channels.m3u
This gives M3U playlists down to an instance level if needed.

**Comment by rocky4546** [comment]
Solution seems to meet the criteria of the issue. Closing.
