### ISSUE TITLE
How can I add my own streaming link?

### ISSUE THREAD

**Issue by 239144498** [cabernetwork/cabernet#27]
I started the program, but I didn't find the option to add a streaming link, and the config.ini didn't have any configuration instructions for adding a url. Trouble to give a hint?

**Comment by ASHuenchuleo** [comment]
Here's a sample config snip I found on the forum thread for this program

> [m3u_plextv]
> label = M3U PlexTV
> channel-m3u_file = https://i.mjh.nz/Plex/us.m3u8
> epg-xmltv_file = https://i.mjh.nz/Plex/us.xml
> enabled = True
> channel-group_name = plex
> player-enable_pts_resync = True
> channel-import_groups = True
> epg-min_refresh_rate = 3600

**Comment by rocky4546** [comment]
Yes, you can add links via the M3U plugin.  It requires a M3U8 file for the channel list and a TVXML file for the EPG.
