### ISSUE TITLE
Question: USTVGO

### ISSUE THREAD

**Issue by richardgetz** [cabernetwork/cabernet#31]
I am trying to bypass the VPN requirement for ustvgo as I am routing my cabernet through a supported connection. Could you provide any advice to what I would need to change to achieve this?

**Comment by richardgetz** [comment]
I removed this line but it doesn't seem to get that far https://github.com/cabernetwork/cabernet/blob/master/plugins/provider_video_ustvgo/lib/channels.py#L63

**Comment by MartinR577** [comment]
I'm seeing a similar issue when using a VPN  I suspect the correct ports are not being passed. Using PIA and the USTVGO web site works fine but not the cabernet plug in. i get the channel list and guide  but no channels will play. 
What connections are supported?

**Comment by richardgetz** [comment]
I might be able to help you a bit now. If you check out my fork you'll see I add a check box to enable "VPN" mode. This basically just tells Cabernet it should allow the VPN only channels. I also added an internal/external port option for the 5004 port so I can route all of Cabernet through a docker container running my VPN. It looks like USTVGO suggests people use Nord but I have VPN Unlimited and it works. The container/repo I use to run the VPN is called gluetun.

https://github.com/richardgetz/cabernet

**Comment by richardgetz** [comment]
If you run my fork in place of your current setup you need to fully remove and refresh your channel data after you enable VPN mode.

**Comment by MartinR577** [comment]
Awesome thank you

**Comment by rocky4546** [comment]
Reviewed the changes and cannot figure out how you are getting the stream uri.  According to your code, the uri is obtained by calling get_ustvgo_stream(), but that returns None.  you skipped around the call get_ustvgo_stream() when the vpn is true on the initial channel gets.  The reason it was there was because USTVGO was not providing a stream uri when the vpn error was produced.

Again... get_channel_uri() calls get_ustvgo_stream() which you skip for the initial channel list, but when the stream is started, it is still called.

**Comment by richardgetz** [comment]
Yea admittedly, the organization of the codebase confused me. My only goal was to allow it to check for VPN only channels and add an optional for broadcast vs connection port. As of now this is working for my setup and it has been some time since my changes so I can't say exactly what you may need to do to make it work with your preferred format.

**Comment by richardgetz** [comment]
Note for anyone that stumbles upon this, VPN Unlimited stopped working for this. I ended up switching to Nord and it works again.

**Comment by rocky4546** [comment]
Since USTVGO is no more, closing this issue.
