### ISSUE TITLE
m3u provider not reading guide data from xmltv file 

### ISSUE THREAD

**Issue by MartinR577** [cabernetwork/cabernet#33]
I may be missing a setting and this was working for some channels when I initially set this up a few months ago but has stopped reading the guide data.
I'm using the following:
m3u file : https://iptv-org.github.io/iptv/countries/us.m3u
xmltv file : https://iptv-org.github.io/epg/guides/us-local/tvtv.us.epg.xml.gz

XMLTV file type gzip 
I have only a few channels selected. an example is 
1934 WNYW-DT5  (Decades)

I verified the channel is in the epg that's downloaded but they are not in the xmltv.xml outputted by cabernet

**Comment by rocky4546** [comment]
iptv-org is no more.  Also, found a few bugs with xmltv import.  they will be out on the next release. (0.9.12.02)

closing since url is no more.
