### ISSUE TITLE
USTVGO GONE

### ISSUE THREAD

**Issue by s66jones** [cabernetwork/cabernet#35]
With USTVGO going offline, can tv247us be an alternative?

**Comment by rocky4546** [comment]
Yep USTVGO is gone so we will need to determine the best alternative plugin...

**Comment by rocky4546** [comment]
possible providers: 123tvnow, 123tv, tv247

**Comment by rocky4546** [comment]
First plugin will be 123tv. tv247 seems to have lots of instability.  Will look into daddylivehd second.

**Comment by rocky4546** [comment]
123tv
- Completed channel data grab from 123tv

**Comment by rocky4546** [comment]
New 123TV plugin available to replace USTVGO under version 0.9.8.0.  Closing issue.
