### ISSUE TITLE
Start Channel Number needs callback

### ISSUE THREAD

**Issue by rocky4546** [cabernetwork/cabernet#37]
When changing the Start Channel Number in each of the streaming plugins, the channel numbers do not change until the data channels are deleted completely and refreshed.  This looses any data updates that were changed, so instead a callback routine to make the updates to the channel number is needed.

**Comment by rocky4546** [comment]
Added callback in 0.9.9.5.  When you change the start channel number it will update the database with new numbers in the display set.

**Comment by merrychrishna** [comment]
https://github.com/cabernetwork/cabernet/releases/tag/0.9.9.8

channel numbers are not showing up in the client

**Comment by merrychrishna** [comment]
nevermind. they show up now after i use the hdhomerun option in emby. or maybe it was using the plutoTV xmltv filter url
http://localhost:6077/PlutoTV/xmltv.xml
