### ISSUE TITLE
pluto tv tab is missing from channel editor

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#42]
pluto tv tab is missing from channel editor after i rebooted my windows pc. pluto tv and pluto tv instance and xmltv is enabled.

![image](https://user-images.githubusercontent.com/59185469/222046976-8ef3490e-6b77-4f45-9f21-7595af3c0b25.png)

![image](https://user-images.githubusercontent.com/59185469/222047134-89ad5332-2479-46ed-9e79-af0b262840a6.png)
![image](https://user-images.githubusercontent.com/59185469/222047238-41a8e63b-0a24-49c5-9c66-e7117aa517a9.png)

**Comment by rocky4546** [comment]
It will be missing until channels are populated into the database. I would need to see a log during the channel retrieval for pluto to determine why it is not working.

**Comment by merrychrishna** [comment]
I managed to fix it by deleting the config file and starting a fresh
config. It happened again after a fresh uninstall and reinstall of
cabernet. I thinks it happens right after I replace your pull request
files. I'm not sure how to get you the logs.

**Comment by rocky4546** [comment]
Well, there are many different ways to get logging.  I personally like to enable file logging in the settings and set it to DEBUG.  The log file then appears at data/logs/cabernet.log
But, I believe you have figured it out.  I suspect the issue is that you are deleting the database files in the data/db folder when you do something causing the issue to appear.

**Comment by merrychrishna** [comment]
All I did was replace the 2 .py files you gave me though, I didn't delete
anything

**Comment by merrychrishna** [comment]
Also I noticed the ffmoeg path was blank on first install again and ffprobe
path was already set. I had to change those again.

**Comment by rocky4546** [comment]
I think you are saying you are creating a new instance of cabernet all the time. Why would you be doing that instead of just doing the upgrade from the home page?

**Comment by merrychrishna** [comment]
I haven't been creating a new instance. I only ever close cabernet before I
reopen it.

**Comment by merrychrishna** [comment]
Oh to do a fresh install Ive been uninstaling cabernet from the windows
control panel and then reinstalled it

**Comment by rocky4546** [comment]
yea, don't do that... Cabernet has an easy way.  (exception: the new tvguide plugin is manual upgrade right now,.. will be fixing that) To upgrade... the "Check for upgrade" task runs once a day and when you hit the home page will let you know there is an upgrade available.  If the task has not run and you know there is an upgrade, go to the scheduled tasks > applications and run Check for Upgrades... Wait a few seconds then go back to the home page.  If you are right, it will tell you an upgrade is available.  All you have to do is click the button.  Once upgraded, just refresh the home page and the version number will update and everything will be upgraded (except the tvguide...)

**Comment by merrychrishna** [comment]
Oh ok sweet. I'll check out all the new stuff either later tonight or
sometime tomorrow during the day. It's pretty awesome that your project is
actively being updated.
