### ISSUE TITLE
tuners im not using being used on channles i dont have.

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#44]
tuners im not using being used on channles i dont have.

the first thing i did before i noticed this was disable most of the pluto tv channels and have reassigned a lot of the ones i am using. but your tuner status is showing 4 tuner in use when im not even streaming pluto tv right now and also i dont even have those channeles enabled.

whats going on here?

![image](https://user-images.githubusercontent.com/59185469/222341839-f42357bd-0fd3-4c5a-a62f-d4593faf5472.png)

![image](https://user-images.githubusercontent.com/59185469/222341504-8240d1ca-a3f1-4e86-8e72-c02fddd130aa.png)

**Comment by rocky4546** [comment]
Even though they are disabled, if a DVR/media server requests the stream, it will provide it.  A log would be able to determine what is going on.

**Comment by merrychrishna** [comment]
ok ive enabled debugging logs and restarted cabernet but after i restarted it those tuners are gone now. ill wait till they show up again.

**Comment by rocky4546** [comment]
If the channels show streaming, then the client is still accepting streaming packets and is acting like it is still streaming the video to the screen.  It can be the way you terminate the stream in your client.  The word "Streaming" has a very specific meaning that the client is still up and accepting the stream.  This normally means it is a client issue.

**Comment by rocky4546** [comment]
Recommend double checking this.  I believe some of the updates will help with this issue having the channel number displayed correctly in the home page... In RC2.

**Comment by merrychrishna** [comment]
its displaying correctly now

![image](https://user-images.githubusercontent.com/59185469/227732071-1a7bfcd5-c3fc-45fc-82ff-98afde48b7ef.png)
