### ISSUE TITLE
ghost tuners in use for daddylive

### ISSUE THREAD

**Issue by vortex91** [cabernetwork/cabernet#51]
When daddy live channel goes down tuner status shows down. then when that channel comes back up the tuner states steaming even though it is not thus using up tuner count and eventualy reaching max tuner count so client cant request new streams.  This happens both with internal proxy and steamlink.  Need to restart cabernet to get rid of ghost tuners not in use by any client.

**Comment by rocky4546** [comment]
Chances are this is an issue with the client.  If the tuner status at anytime says Streaming, that means the client is connected and recieving/accepting data.  So, if the client has the connection but is not displaying the video, then it is a client issue.  When the user stops displaying a channel, the client is expected to terminate the connection to Cabernet.  Until that connection is terminated by the client, Cabernet will continue to provide the stream to the client.
