### ISSUE TITLE
plutotv: i can no longer see segments to be filtered

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#53]
in pluto tv i can no longer see the segments to be filtered even when i set the system log handler to "INFO"

**Comment by merrychrishna** [comment]
oh maybe its because im using streamlink?

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/227372398-de1eeb77-7c4c-475a-ae29-9e1e3622534f.png)

**Comment by merrychrishna** [comment]
i guess we dont need to see the segments anyway since streamlink automatically filters them

**Comment by rocky4546** [comment]
No filtering of segments available from Cabernet with streamlink.  Serving at the INFO level is displayed, so there is no issues. Closing issue.
