### ISSUE TITLE
feature request: please can you add pluto tv animated splash screen in place of frozen stream due to segment filtering

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#54]
feature request: please can you add pluto tv animated space travel splash screen in place of frozen stream due to segment filtering?

maybe you could add a stream recorder of some sort with a bit of a delay that allows you time to insert the splash screen when the screen freezes during commercials and then resumes the show after the commercial freeze. so basically 2 streams will be playing but only the recorded stream will actually get outputted to the clients.

**Comment by rocky4546** [comment]
The ability to disable filtering is already implemented, denied.

**Comment by merrychrishna** [comment]
but if i disable filtering it freezes, you know this already. so why are you telling me to disable filtering? thats not the same thing as what i described.

**Comment by rocky4546** [comment]
if it freezes, then that is something you could write up and someone could take a look, but adding a snippet will not happen.
