### ISSUE TITLE
Will this ever support bell's fibe tv?

### ISSUE THREAD

**Issue by Baggette** [cabernetwork/cabernet#55]
It would be great to integrate bell's fibe tv thing into my media server, based on what seems to show up in the network tab I think it does use m3u but not sure if it is possible to "rip" them.

**Comment by rocky4546** [comment]
If you have the m3u file, you can create an instance of the m3u plugin and ingest the file to see what happens. To do that, just edit the config.ini file and add something like
```
[m3u_fibe]
Label = M3U FibeTV
```
then restart Cabernet to pick up the config changes.  The website will then have the instance available for editing.  Once you have added the location of the m3u, enable the instance and restart cabernet to have the instance start.
