### ISSUE TITLE
Custom User-Agent

### ISSUE THREAD

**Issue by itprotj** [cabernetwork/cabernet#56]
I am experimenting with grabbing some channels from various providers and some rely on having a browser user agent to work.
Is there an option I am missing or some sort of configuration parameter I can adjust to customise the user agent string that Cabernet sends when grabbing the stream?

Thanks

**Comment by rocky4546** [comment]
Currently the User-Agent sends the Firefox Browser text.  It is not available to adjust in the settings, but if you want to try other browsers, you can set it by editing the utils.py at cabernet/lib/common/ to see if other strings will work.  I just updated it in RC2 to Firefox version 111.0
