### ISSUE TITLE
m3u source transforms url incorrectly

### ISSUE THREAD

**Issue by warrentc3** [cabernetwork/cabernet#59]
Pluto works fine...
{
            "ChannelId": "612fea0e970e6f00083be56b",
            "CallSign": "TV Land Drama",
            "GuideNumber": "0",
            "GuideName": "TV Land Drama",
            "URL": "http://192.168.245.102:5004/PlutoTV/watch/612fea0e970e6f00083be56b",
            "HD": 1
}

ChannelsDVR M3U does not...  also unclear what criteria determines "HD".
{
            "ChannelId": "13",
            "CallSign": "GTN",
            "GuideNumber": "13",
            "GuideName": "GTN",
            "URL": "http://http://192.168.245.101:8089/devices/ANY/channels/13/stream.mpg?format=ts&codec=copy",
            "HD": 0
}

**Comment by rocky4546** [comment]
provide m3u section please

**Comment by warrentc3** [comment]
sure, but it's even happening w/ these https://i.mjh.nz/Plex/

#EXTINF:-1 channel-id="plex-5e20b730f2f8d5003d739db7-62d1ecc8e44d39da220722aa" tvg-id="5e20b730f2f8d5003d739db7-62d1ecc8e44d39da220722aa" tvg-logo="https://provider-static.plex.tv/f/epg/channels/logos/gracenote/ff75dc12d5abb10dff1ec781ae19c566.png" , ALF
https://epg.provider.plex.tv/library/parts/5e20b730f2f8d5003d739db7-62d1ecc8e44d39da220722aa.m3u8?X-Plex-Client-Identifier=4f10a11d0159055e-com-plexapp-android&X-Plex-Client-Platform=Android&X-Plex-Token=7yUi7zo6-iY4kp2RnLRw

becomes

{
            "ChannelId": "5e20b730f2f8d5003d739db7-62d1ecc8e44d39da220722aa",
            "CallSign": " ALF",
            "GuideNumber": "12",
            "GuideName": " ALF",
            "URL": "http://https://epg.provider.plex.tv/library/parts/5e20b730f2f8d5003d739db7-62d1ecc8e44d39da220722aa.m3u8?X-Plex-Client-Identifier=4f10a11d0159055e-com-plexapp-android&X-Plex-Client-Platform=Android&X-Plex-Token=7yUi7zo6-iY4kp2RnLRw",
            "HD": 1
        }

**Comment by rocky4546** [comment]
I tried a Plex segment and it worked fine. I placed this in a file and set it to import on my m3u test instance.
#EXTINF:-1 channel-id="plex-5e20b730f2f8d5003d739db7-61ddcdc03c12aa1e5d320aaf" tvg-id="5e20b730f2f8d5003d739db7-61ddcdc03c12aa1e5d320aaf" tvg-logo="https://provider-static.plex.tv/epg/cms/production/b4de0c09-34ab-452f-9dfd-c28dc607af6d/CaughtinProvidence_1500x1000_lightbgd.png" group-title="USA" ,  Caught in Providence
https://amg00353-lionsgatestudio-caughtinprovi-plex-42z14.amagi.tv/playlist/amg00353-lionsgatestudio-caughtinprovi-plex/playlist.m3u8?us_privacy=1---&did=62274240-07e7-5d94-8dc8-ef68cf19e175&dnt=0&X-Plex-Token=7yUi7zo6-iY4kp2RnLRw&channelId=61ddcdc03c12aa1e5d320aaf&device_id_type=&ifa_type=ppid&url=app.plex.tv&app_name=plex&app_bundle=com.plexapp.android&app_store_url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.plexapp.android&gdpr=0&gdpr_consent=0&coppa=0&ua=okhttp%2F4.9.0&ip=185.236.200.172&brand_name=&device_model=&device_type=handset&w=&h=&partner_id=CIP0176&ads.us_privacy=1---&ads.did=62274240-07e7-5d94-8dc8-ef68cf19e175&ads.dnt=0&ads.X-Plex-Token=7yUi7zo6-iY4kp2RnLRw&ads.channelId=61ddcdc03c12aa1e5d320aaf&ads.coppa=0
I requested the m3u file and played it in the vlc player just fine.  Also looked at the database and all was good.  Will try your specific m3u next.

**Comment by rocky4546** [comment]
I found a path where it happens.  If you select m3u8proxy AND select the lineup.json, you get the issue.  If you use m3u outputs or not use the m3u8proxy, it does not happen.  Looking into why it happens in this special case.

**Comment by rocky4546** [comment]
Problem has been resolved.  It will be in the next release

**Comment by rocky4546** [comment]
Cabernet 0.9.11.01
