### ISSUE TITLE
501 not implimented when trying to update from ui

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#61]
501 not implimented when trying to update from ui. the update never starts.

![image](https://user-images.githubusercontent.com/59185469/228966478-ccd712a0-3be4-46c0-a3c0-48ac07d1b4ec.png)

**Comment by rocky4546** [comment]
yep, found an issue with RC2 as well, just like RC1.  After that updates are back to normal.

**Comment by merrychrishna** [comment]
oh ok. so i just have to delete the plugins file? or do you want me to install the exe file ovretop?
