### ISSUE TITLE
Cannot use the hdhr interface from plex

### ISSUE THREAD

**Issue by dcardin** [cabernetwork/cabernet#68]
I unchecked the "disable_hdhr" setting, the netmask matches my network. Both Plex and Cabernet are on the same IP.
When I try adding the streams from cabernet to Plex Live TV, it's not showing up. I cannot either use the IP:65001 assumed bound port. 

Is this supposed to work? Have I missed a step?

**Comment by rocky4546** [comment]
There are a number of things that have to happen to get the hdhr interface (UDP PORT 65001) to fully work.  One is the web portal must be moved to port 80.  If you don't want all that issue, then disable the hdhr interface (UDP port) and interface with Plex, normally.  Do this like normal hdhr simulated devices do...
First, I recommend you set in Cabernet the settings > Client > EPG > Use Channel # for Channel ID to True.  then in Plex...
1) Don't see your HDHomeRun device? Enter its network address manually
2) Enter http://ipaddres:6077 and connect
3) Find the device on the list and setup device
4) Have an XMLTV guide on your server? Click here to use it.
5) http://ip address:6077/xmltv.xml click continue
6) Continue as normal to setup the tvguide.

if plex is having a fit on the delays it takes to get the xmltv.xml file.  Try to get the file from the browser and save it locally to the plex server.  Then enter the xmltv.xml location such as /home/user/xmltv.xml
