### ISSUE TITLE
epg data none Version: 0.9.12.01

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#71]
[cabernet.log](https://github.com/cabernetwork/cabernet/files/11154111/cabernet.log)

my epg is empty now after the update. Version: 0.9.12.01

**Comment by rocky4546** [comment]
what have you set for epg hours to pull in the plutotv settings?

**Comment by merrychrishna** [comment]
48 hours

**Comment by rocky4546** [comment]
that could be the issue.  Clear the field and save.  That will set it back to default.

**Comment by merrychrishna** [comment]
whats the default again?

**Comment by rocky4546** [comment]
clear the field and save.  That will set it back to default

**Comment by merrychrishna** [comment]
that didnt quite work until i restarted cabernet from the ui

**Comment by merrychrishna** [comment]
[cabernet.log](https://github.com/cabernetwork/cabernet/files/11154385/cabernet.log)
heres the logs just encase
