### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#74]
can you setup a discord server?

**Comment by rocky4546** [comment]
Nope

**Comment by dcardin** [comment]
Lack of interest or no desire to manage it ?

**Comment by rocky4546** [comment]
Tell you what... You set it up, administer it and maintain it and I will add the link you provide to the footer of Cabernet for people to use.

**Comment by merrychrishna** [comment]
@dcardin ive set one up before but i dont really want to manage one either lol. hopefully someone will come along that does.

**Comment by dcardin** [comment]
@merrychrishna  what's involved in the management? I mean, ultimately we just want a channel where people can talk about cabernet and contribute?

**Comment by merrychrishna** [comment]
you will have to probably disable things like links and pictures from being shared encase of spam or stuff that will get your account banned. i think nsfw stuff already automatically get blocked by an algorithm. and i think you  will need to find a bot to block racist comments which i havent done before but i think might be easy. and youle need to give poeple roles like admin rols so only admins can see certain channels. or could setup like a waiting room where people cant see other channels until they verify a phone number and are given a rol to see all the channels. before they are given a role they could be in a channel where they cant post links or pictures, this will cut down on some spam. you could manually give people in the waiting room a role to have higher priveledges without making them admins, again this is just to cut down on spam from bots accounts. i dont know how to setup automatic role assignment like when you can react to a rules page to get automatically assigned a role though.

**Comment by dcardin** [comment]
No wonder nobody wants to do it. Guess it'll be github discussions, unless we end up having a lot of volume, which would justify spending time on it, I think. Thanks to you both

**Comment by merrychrishna** [comment]
theres a discord bot named bernard that blocks key words like racist words and such and auto kicks peeople too that acn be added to the server.

**Comment by merrychrishna** [comment]
that would hep with not having to manage the server all the time by manually kicking poeple
