### ISSUE TITLE
Beginners setup, Having some trouble setting up my config.ini

### ISSUE THREAD

**Issue by Nostradamus1973** [cabernetwork/cabernet#78]
Good morning Everyone,

Unfortunately, I wasn't paying attention and I had posted this yesterday in a closed thread, this is(mostly) what I wrote:

I've been working with @cookieisland to get things rolling in Docker and he's been awesome, but, now I've gotten stuck on my config.ini file and it was conveyed to me that @rocky4546 is the best to try and figure out the mess I've gotten myself into. lol

Before I drop my config details on here, allow me to explain what's been happening with Jellyfin 10.8.9, the problems I'm experiencing are parts of my guide look good, except the numbering seems to resemble the meta data(I think for Xumo), if that makes sense. On other parts of my guide the icons are gone and others the channel name is there and the rest is void, and some have very generic EPG info like channel name only, if that makes sense.

config.ini:

```

[hdhomerun]
hdhr_id = 105029CB

[display]
theme = blueradiance
display_level = 3-Advanced

[tvguide]
enabled = True

[epg]
genre = normal
epg_prettyprint = True

[daddylive_default]
label = DaddyLive Instance
enabled = True
channel-import_groups = False
player-enable_url_filter = False
epg-prefix = 3000
channel-start_ch_num = 1

[tvguide_daddylive]
label = TVGuide DaddyLive
enabled = True

[daddylive]
enabled = True
epg-plugin = ALL

[m3u_default]
enabled = True
label = m3u_default

[m3u_PlexTV]
enabled = True
label = m3u_PlexTV
channel-m3u_file = https://i.mjh.nz/Plex/us.m3u8
epg-xmltv_file = https://i.mjh.nz/Plex/us.xml

[m3u_SamsungTV]
enabled = True
label = m3u_SamsungTV
player-tuner_count = 20
channel-m3u_file = https://i.mjh.nz/SamsungTVPlus/us.m3u8
epg-xmltv_file = https://i.mjh.nz/SamsungTVPlus/us.xml
epg-prefix = 4000

[plutotv_default]
enabled = True
label = plutotv_default
epg-plugin = ALL
channel-thumbnail = colorLogoPNG
epg-enabled = True
epg-prefix = 4500
channel-start_ch_num = 1

[tvguide_plutotv]
label = TVGuide PlutoTV
enabled = True

[plutotv]
enabled = True
epg-plugin = ALL

[xumo_default]
enabled = True
label = xumo_default
epg-plugin = ALL
epg-prefix = 5000
channel-start_ch_num = 1

[xumo]
channellistid = 10006
enabled = True
epg-plugin = ALL

[tvguide_xumo]
label = TVGuide Xumo
enabled = True

[m3u_samsungtv]
enabled = 1
channel-start_ch_num = 1

[m3u_plextv]
enabled = 1
epg-xmltv_file_type = xml
epg-prefix = 3500
channel-start_ch_num = 1

[tvguide_default]
label = TVGuide Instance
enabled = True
```
There you go, I know it looks VERY rough, but, I was trying a few different things in an effort to get things running properly.

Thank you :)

**Comment by Nostradamus1973** [comment]
I removed these:

```
[m3u_samsungtv]
enabled = 1
channel-start_ch_num = 1
epg-xmltv_file = https://i.mjh.nz/SamsungTVPlus/us.xml

[m3u_plextv]
enabled = 1
epg-xmltv_file_type = autodetect
channel-start_ch_num = 1
epg-xmltv_file = https://i.mjh.nz/Plex/us.xml
```

They looked superfluous, and nothing seems to have changed after removing those lines.

**Comment by rocky4546** [comment]
Your config.ini looks like a pretty big mess.  Cabernet allows you to configure how you want to, but it looks like you have chosen multiple configure types on top of each other. Also, you have shown a user error that I need to block.  The section names in the config.ini must be all lower case and you have upper case letters in the names.

To start, we need to determine how you want to handle channel numbers.  You can use the start_ch_num or the epg-prefix, but not both.  You, of course, CAN use both, but the results may be confusing.  Here is the definition.  start_ch_num, when changed, will renumber the channel numbers from the number given incrementing the channel number for each channel in the list.  This is nice for providers like pluto that have channels that are spaced apart.  plutotv has a range from 0 to 3450, but only contains 376 channels, so it might not be a good use of channel numbers to renumber them using start_ch_num.  Using start_ch_num will renumber the channels from x to x+376.  The issue is when a new channel appears, it will add it to the list with the channel number from pluto, so you could see duplicates. epg-prefix offsets the channel number, so if you have a epg-prefix of 4500, then the channels will go from 4500 to 4500+3450. If a new channel comes in, then it will not have a conflict since the start_ch_num was not used.  Also, the status on the home page is based on the channel number in the channel editor, so it you use epg-prefix, the number on the status page will not match what is in jellyfin.  If you use the start-ch-num, then the channel numbers will match.

Let me know which way you wish to proceed on the channel numbering.

**Comment by Nostradamus1973** [comment]
Thank you for taking a look at my config.ini file, I figured it was a hot-mess given I'm still learning about  Cabernet lol; I would like to make the config.ini file functional and concise where everything runs smoothly.
Originally I wanted to have the numbers start after 3500, I have some scraped channels that reside in the 3000-3499 block it's below half capacity and I'm kinda happy leaving it that way with room to grow.The 3000-3499 set of channels originally were used as a backup to my emby installation, long story for another time.
But, after thinking about how you have things set, I can STILL keep my backup channels after Cabernet's set of channels with Jellyfin. So, I would like to keep the way you have it setup, have Cabernet order the plugins and any m3u's I add manually following that same order.
I will go ahead and exchange any Captical letters in the config.ini while I wait for you to get back to me.

I gotta tell you, even though only some of the things are working on my instance of Cabernet, I can really say I'm impressed with your project, it's a pretty bad ass application that does some pretty amazing things. I wish I had crossed paths earlier with it.

Thx @rocky4546

**Comment by Nostradamus1973** [comment]
I tried changing the section names from capitals to lowercase and I broke my docker instance,  for example, I changed [m3u_SamsungTV]  to [m3u_samsungtv] and label = m3u_SamsungTV to label = m3u_samsungtv.
After that the ports became inaccessible. 
So, I'm thinking I did it wrong, I think I will wait to see what you say.

**Comment by rocky4546** [comment]
well, you dud not answer the question... which way do you want to do channel numbers...

**Comment by rocky4546** [comment]
Not quite.  Both start at a certain number ( you said "this(start_ch_num) will start with 1").  The difference is epg-prefix just adds that number to the current channel number.  start_ch_num RENUMBERS the channels starting at the number provided (basically compressing the channel number list).  epg-prefix occurs between cabernet and the client while start_ch_num occurs within cabernet. 

As stated above for pluto: "Using start_ch_num will renumber the channels from x to x+376. " while "if you have a epg-prefix of 4500, then the channels will go from 4500 to 4500+3450", which is a much larger range of channels used.  You are correct. epg-prefix will just do an adjustment on the fly, so as channel numbers change or added from the provider, they will auto change to the client, unlike the start_ch_num.  I find using high numbers like you are using means (when using start_ch_num), new channels end up at the start of the channel list, so it is obvious which ones are new.

Let us assume you are going with start_ch_num as you have indicated.  The next step is to disable all instances except one.  We will add one plugin at a time until all plugins are enabled and configured correctly.

So next question... which plugin/instance is the first one you wish to configure?  Once you have decided that.  Go to the data mgmt  >Delete Instance and delete all instances for the plugin you are going to setup.  Also, edit the config.ini and remove all lines associated with the plugin.  Add back in only the two lines required to start working with the plugin.  If the plugin is pluto, then add
[plutotv_default]
Label = PlutoTV Instance

Restart the app and double check that data mgmt has no listings for the plugin.  Last thing. I assume you are using the HDHomerun interface to jellyfin and not the m3u interface.

**Comment by Nostradamus1973** [comment]
Okay, I'm going to get started on that right now and disable all instances except one.

And as soon as I read your mention of HDHomerun just now, I instantly remembered reading a post that mentioned using the HDHomerun interface, I think I remember reading it helped mitigate the artifacts like pausing from commercial. And that's totally on me, I didn't change it because I was used to working with m3u's and assumed I could overlook something if I used the HDHomerun interface. I will change it the HDHomerun interface after handling the config.ini
I'll be back as soon as I finish the edits.
Thx again.

**Comment by Nostradamus1973** [comment]
So, I've used Chrome and Firefox to try and remove the instances(in data Mgmt) with no luck whatsoever. Then,  I removed the plugins thinking that would help, and it didn't; I even went into my config.ini and edited it down to this:

```
[hdhomerun]
hdhr_id = 105029CB

[display]
theme = blueradiance
display_level = 3-Advanced

[tvguide]
enabled = False

[epg]
genre = normal
epg_prettyprint = True

[daddylive_default]
label = DaddyLive Instance
```
After removing the lines containing the instances I still see them in Data Mgmt. Should I stop it and repull the image?

**Comment by Nostradamus1973** [comment]
After a second restart using docker, they finally disappeared from the Channel Editor, however, they are still being listed in Data Mgmt.

**Comment by rocky4546** [comment]
I am curious.  Can you take a screen shot of the pull down in datamgmt for instances and post it here.  You can create a image file, then drag it to the issue to post it.

**Comment by Nostradamus1973** [comment]
I got a Something went really wrong and can't process the file, [here's the ibb-link for that screenshot](https://ibb.co/n1Fb5Yh).
The plugins are all gone from the Channel and EPG sections

**Comment by rocky4546** [comment]
Try upgrading to 0.9.12.06.  It has a fix for deleting instances from data mgmt.  Your pic looks fine.

**Comment by Nostradamus1973** [comment]
Okay, I recreated/repulled the image and you are correct, the upgrade fixed that problem. I did a restart via Scheduled Tasks --->Applications and it seemed more responsive.

**Comment by rocky4546** [comment]
Checked and it looks like Cabernet is checking the plugin database which will have daddylive in it even though there is no instance to generate.  Will probably make a change so it really can be removed in Data Mgmt, but for now we can proceed.  So, the first one is DaddyLive.  It is unique in that it has an option to integrate with TVGuide.  Based on the above statements, I assume TVGuide is not listed in the Data Mgmt list? If so, lets configure Daddylive

1) There should be no instances of TVGuide listed under the EPG Providers.
2) TVGuide plugin should be installed as listed in the Plugins area
3) DaddyLive Setting = Change the EPG Plugin to Use: ALL
4) Daddylive Instance = leave Starting Ch Number alone for now.  It only works once we have channels
5) Daddylive Instance = Enable it
5) Daddylive Instance = EPG days to load: 2

Restart the app.  It should configure and turn on tvguide automatically and start creating the channel list and the EPG.  Let it run.

**Comment by Nostradamus1973** [comment]
Yes, ,TVGuide is not listed in Data Mgmt, and is in the Plugins area and not installed.
I'm going to take care of those settings now. BRB :)

**Comment by Nostradamus1973** [comment]
Okay, it won't let me proceed after I tried: DaddyLive Setting = Change the EPG Plugin to Use: ALL
It says:
Updated [daddylive][epg-plugin] to ALL
[daddylive][epg-plugin] EPG instances are not installed, aborting change

But, I'm going to try and move foward till I restart, if the changes won't apply because of the aborting then I'll install TVGuide...

**Comment by Nostradamus1973** [comment]
Channels are populating and showing up in channel editor.
 I just got a natural rush of dopamine, this has been a bit of a roller coaster ride for me over the last few days. LOL!
Okay, what's next?

**Comment by Nostradamus1973** [comment]
Yes, I changed the starting number to 100, saved it, then went to the editor and the channels are now counting up from 100. 
With Jellyfin, I went to use the HDHomerun interface and couldn't get any of the HDHomerun  links to work. Is there some specific way to get the links to work? Or, should I just stick with the m3u for the time being?

**Comment by rocky4546** [comment]
no going backwards... When you add a HDHomerun link, you add it without the end part. With jellyfin, you can add by plugin or for all.  I add with all myself in emby. So to add all, use
http://ipaddress:6077/
for a plugin use
http://ipaddress:607/Daddylive/
Then you get to the xmltv.xml part, I use a file-based pull with a cron job, but for now, you can use the xmltv.xml url directly.

**Comment by Nostradamus1973** [comment]
Yes, that worked, it accepted the HDHR link, and I loaded the xmltv.xml
I restarted Jellyfin and I don't see the channels or guide yet, so, I'm going to restart Cabernet and then Jellyfin again and refresh the guide data

**Comment by Nostradamus1973** [comment]
Okay, restarting Cabernet and then Jellyfin did the trick. The guide is loading, however, only half of the channels have guide info, I didn't edit them down yet, but, Jellyfin can be difficult when it comes to accepting new guide info(something emby does much better), so, the rest may load at a later time. The numbers look great, they correspond to the ones in the channel editor.
What's next?

**Comment by rocky4546** [comment]
That is correct.  Only about 70 channels will have guide data.  the other channels are not listed in the tvguide site, so nope, they have nothing.  You can keep all those non-us channels, but lets say you want to have the us channels.

Go to the Channel Editor > Thumbnail column and enter the word blank in the filter.  this should filter to all those channels without a thumbnail.  then click the top checkbox in the first column twice to remove the check box on all remaining channels and click Save Changes.  this will give you the list of us channels that have guide data.

**Comment by rocky4546** [comment]
Before we move on... It would be appropriate to not increase the TVGuide data from 2 days to 14 all at one time, unless you want lots of attention from the provider... The recommendation is to increase the days slowly by adding 2 days every 24 hours.  I have mine set at 10 days, but you can get it to whatever level you want.

So, the next plugin will be much easier.  Shall we try the xumo and pluto or are we skipping those?

**Comment by Nostradamus1973** [comment]
Okay, I will take your advice and wait at least 24 hours before increasing it by 2 days.
Yes please, let's go ahead with xumo and pluto.

**Comment by rocky4546** [comment]
add the next two lines in the config.ini for xumo_default and plutotv_default with their labels like we did with daddylive.
Since we don't have dependencies with other plugins, when you reboot, the instance should appear (disabled) and ready to configure.  In this case, I would recommend keeping everything with defaults for now.  Enable both instances and restart.  It should all come up and once you have the channel list, you will need to decide where to start the next set of channel numbers.

**Comment by rocky4546** [comment]
Plutotv is special in that it filters out the commercials.  This is because the "discontinuity" errors that are caused by them.  In short the commercials are on a different timeline causing significant errors.  To handle this, Cabernet removes the commercials. BUT... this causes many people pain since watching live will mean a black screen during commercials.  If you record plutotv shows, the time will be shortened by the commercials and play as if they were never there.

**Comment by Nostradamus1973** [comment]
Okay, I added those 2 lines and got the xumo and pluto plugins to finally show up. It would probably be safe to start the next plugin after  400, that way there's slight overhead and less change of change affecting things, I think. LOL Pluto is next in line, so, I will start that at 400 and 800 for xumo. Would that work okay?

**Comment by rocky4546** [comment]
insufficient info for me to tell what is happening.  all I can read is something is wrong.

**Comment by Nostradamus1973** [comment]
Okay, I changed the starting number of Pluto to 600 and 1000 for Xumo, now everything seems to look correct, albeit the guide is missing.
Looks like we're back on track, I'm going to wait for you before I move onto the next step because this may act as a nice tutorial for other would-be Cabernet users.

**Comment by rocky4546** [comment]
I found that JellyFin and Emby are doing something similar to Plex.  It is using the URL as the channel number instead of the channel number, so some of the issue you are seeing is missed correlation between channel lists and EPG.  You can see it by going to Jellyfin under settings for Live Tv, selecting Cahnnel Tab.  The edit one of the plutotv channels.  You should see a very long uid shown instead of the channel number for the guide data channel.

To have a better correlation, I have a new version 0.9.12.07 that should help.  Once upgraded, go to the Client Settings under EPG and change "Use Channel # for Channel ID" to true.   No restart needed.  All I did was go into Emby and request a guide refresh. check the same thing in JellyFin again and this time the channel number should appear correctly.

**Comment by Nostradamus1973** [comment]
After pulling/recreating the image I hadta reinstall the plugins, no biggie there. 
I did a systemctl restart of Jellyfin because the guide wasn't populating, that didn't seem to fix anything, which prompted me to restart Cabernet, one thing I did notice is that I am unable to refresh the EPG's and corresponding channels under scheduled tasks within Cabernet.

Could that be part of the problem too?

**Comment by Nostradamus1973** [comment]
I take some of that back, I am able to refresh The Daddy Live EPG, but, not pluto or xumo, and as far as the channels, I can't refresh any of them(DaddyLive, pluto, xumo).
I do have a some of the guide showing up for Daddy live, and nothing for pluto or xumo.
Historically I've noticed Jellyfin can be difficult accepting new guide info, there are mentions of this caching issue online, however, after a restart or two, it will finally accept the new guide data.

**Comment by Nostradamus1973** [comment]
Okay, now that that all looks great.
What's next? M3U-plugin?

BTW, thanks, this is very educational for me and tackling these things one at a time is definitely best as you suggested, I'm actually enjoying myself on this tutorial you're giving.

**Comment by rocky4546** [comment]
Looks like you are getting use to using Cabernet.  Now for M3U.  Unlike the unique plugins M3U plugin is setup, generically. It is up to the user to determine the best settings, while the unique plugins have their default settings set to the best.  Although Cabernet InternalProxy is very powerful, I have found streamlink to be a good app for novices.  Streamlink uses the URL it is sent to determine which of many plugins it has to connect to the provider. So, in a sense, it auto-sets the configuration of streamlink based on the URL.

Streamlink is not installed as part of Cabernet, so you should do that.  It needs to be the latest version (5.x) to work. There is some info on the forum on how to install it, but I believe using python pip works.  Once you have it installed, you need to check if it works with cabernet.  Try setting daddylive to streamlink and then trying a channel.  Watch the logs to see if there is any issue and the video plays.

**Comment by cookieisland** [comment]
> After pulling/recreating the image I hadta reinstall the plugins, no biggie there.

The reason you had to reinstall the plugins is because your docker-compose.yaml only maps the cabernet data directory which is /app/data. Therefore every time you pull a new docker image you will have to reinstall the plugins becuase the new docker image will have an empty /app/plugins_ext directory which is where the plugins are stored.  At minimum I recommend also mapping a directory on your host to /app/plugins_ext and then you will not have to reinstall the plugins after every docker pull. Better yet I recomemend you map the entire cabernet directory to /app (which includes both /app/data and /app/plugins_ext) because that will avoid a problem where you will run out of disk space in the future (it will take quite some time but you will ultimately run out of disk space).

**Comment by Nostradamus1973** [comment]
Thx @rocky4546 and @cookieisland for getting back to me.

I'm running version 0.9.12.07, so, would that mean streamlink is installed? I don't see it in Ubuntu, but, given that the docker is self contained, I'm probably missing it.

@rocky4546 Once I have this config.ini running smoothly, I'm down to wipe it and do it your way; I usually take advice from seasoned user's/creator's, I just wanted to make sure this was going to make my life easier, which, it looks like it definitely will, that-being-said, there are so many OTHER things it does well, which has me all-in on it. I think a good week of use and I'll probably start fresh your way.

So, if Streamlink is installed. What's next?

**Comment by rocky4546** [comment]
As stated above, test it by setting daddylive stream type to streamlink and try playing a channel while looking at the log file.

**Comment by Nostradamus1973** [comment]
I'm sorry, I got ahead of myself, I hadta enable the logs to verify that Streamlink is working:

`2023-04-12 18:45:12,158-INFO:streamlink_proxy Serving`

What's next?

**Comment by rocky4546** [comment]
We will have a few things to setup AFTER getting the M3U up and running, like schedule updates of the channels and EPG, but before that, change daddylive back to internalproxy and setup our first m3u instance in the config.ini.  Restart the app and then configure the instance.  Try setting:
1. The stream to streamlink
2. Enter the url for the m3u8 file (either compressed or not
3. Leave the file type to autodetect. (it works like MS Windows by using the trailer of the filename)
4. Change the "Non-VOD Segments to Start" to a higher number if you want more buffering.  It is normally about 5 seconds per segment.  If you enter 100, then it will send as many as the provider lists up to 100.  Normally, this is a number between 2 and 6 segments from the provider.
5. Enable PTS/DTS Resync is normally enabled, but you can try disabled first and if you don't get time issues (like a 30 min recording is listed as 10 hours long), then it would be better turned off.  It basically tries to resyncs the timestamps using ffmpeg.
6. Enter the URL for the xmltv.xml file

Once all that is done, enable and restart.

Now you can go through the same procedure you did before checking the channel editor, moving the channel numbers, confirming you have EPG data and pushing the info to the client.

Also, you can try to set the stream type to m3uredirect.  This causes cabernet to send the m3u8 data to jellyfin and assume it will connect directly to the provider.  Cabernet does nothing in this case.  Some media servers cannot handle the direct stream, but you can try it. Some like the m3uredirect for m3u instances.

**Comment by Nostradamus1973** [comment]
Okay, I'm going to get started on all that right now, I'll be back when I'm done or get stuck.

**Comment by Nostradamus1973** [comment]
Okay, I've been playing around with some settings after adding the m3u's for plex and samsung, I even  tried the m3uredirect without much luck, but think I will revisit that setting at a later point. 
I do have one more question before I gotta head out for the night. Now that I have the two m3u's(plex/samsung) loaded under one m3u in the channel editor, I can't seem to save any of the channels when I try to tick to enabe/disable, so, it's loading the entire channel set's for plex and samsungtvplus at the moment. Could this be a bug? The channels I edited prior to the update I can no longer change either.
Thx

**Comment by rocky4546** [comment]
Which m3u8 files did you pull?

**Comment by Nostradamus1973** [comment]
I just tried 2 to start off with, Plex and SamsungTV Plus
I'm gonna pull the new image as you recommended right now.
I'll BRB and let you know if things are fixed.

**Comment by rocky4546** [comment]
ok, it is in github now.  try 08 again.

**Comment by Nostradamus1973** [comment]
Right on, the upgrade worked and that fixed the problem.

**Comment by rocky4546** [comment]
Still wondering which files you used.  Basically wondering how many channels you tried to import into the M3U plugin. 

Next on the list is the scheduler.  It is currently empty (except for startup.  Since each m3u and xmltv.xml file has a different required update rate, you need to determine how often to update the data from the URL provided.

**Comment by Nostradamus1973** [comment]
I think I understand, I had a similar situation with a script that ported ustv-go, they(ustvgo) scrambled the channels twice an hour so, the script would update twice and hour and I would do the same on my end with the guide twice an hour and then more 4 times an hour.
So, instead of one, I have to take into consideration 4+, and instead of using Jellyfin, I'll be using Cabernet. So, if Cabernet does all the heavy lifting, then Jellyfin would only need to update for whichever m3u has the shortest lifespan. I think. lol
I gotta run out to eat, but, I'll be back in roughly 2 hours.
Thx again

**Comment by rocky4546** [comment]
And something you may want to do... once you get days of daddylive EPG and all the M3U instances imported, you may find that it takes a very long time to push the entire xmltv.xml file to Jellyfin.  Due to this, Jellyfin may timeout.  If this happens, you can setup a cronjob between Cabernet and Jellyfin to pull the xmltv.xml file every so often.  I then find the media server can pull the xmltv.xml file in seconds.  Biggest issue is all the timing of how often and when to pull what.  Since I have multiple media servers like TVHeadend and Emby, I use the cronjob to pull the xmltv.xml file once and then tell all the media servers to get that file from the system.

Also, if you turn prettyprint off in the Client EPG settings, it will go much faster.

**Comment by Nostradamus1973** [comment]
Okay, good to know about the cronjob, I have a pretty fast connection, so, that might help mitigate the problem, but, I know it's also dependent on who's serving up the info, so, I will keep an eye on the logs of JF.
Is there a timetable I can access that will tell me how often the providers are changing things up and how long each retains the guide? Or, is this the sort of thing that requires finesse and must be done relative to the feedback(info/lacking-info) of each provider?

**Comment by rocky4546** [comment]
All are different.  The site https://i.mjh.nz/ has timestamps that let you know when an update has occurred.
