### ISSUE TITLE
Difficulty trying to add *.json instead of using a *.m3u without luck using the plugin

### ISSUE THREAD

**Issue by Nostradamus1973** [cabernetwork/cabernet#86]
Good Morning,

I've been using(and exploring the features of) Cabernet for a little bit now and I'm loving it!

So, when I read on the linked tvHeadend forum I saw that Cabernet can run the likes of Foxtel which uses a json file, so, I figured I'd try it with Flash TV which uses a json file as well. Unfortunately after playing around with cabernet I couldn't get it to work.
Am I missing something? Or was that a typo on Tvheadend's forum?

Thank you and have a nice day.

**Comment by rocky4546** [comment]
I did do a cleanup a while a go and removed all the json files, but the site keeps converting to json.  The problem with json is that it needs to have three things to work.  The UID or channel number, the channel name and the URL for the stream.  Most if not all of the json files only have the channel number and name.  This means there is no info on how to get the stream, so, yea, it won't work.

The other issue with json is that there is no defined value names being used for channel data, this means, even if it contained the URL, it would be unique in its name/value pairs.

I will go through and cleanup the list again...

**Comment by Nostradamus1973** [comment]
Thanks for getting back to me and explaining how it works. I thought maybe Cabernet could read the json files much like HDhomerun does and Viola. I did notice online converters can change json to m3u and vice versa but that looks messy and Cabernet is clean and sleek, meaning it just works and I want to make my life easier and not more hectic.

Are there other resources than mjh that would have an m3u for flash/foxel?
I know this has nothing to do with Cabernet, BUT, does anyone know why mjh links the json files if nobody can use em?

Thx again and have a great day.

**Comment by rocky4546** [comment]
https://www.matthuisman.nz/2017/07/new-updated-nz-iptv-files.html
