### ISSUE TITLE
Unable to get plugins working

### ISSUE THREAD

**Issue by MatthewC1314** [cabernetwork/cabernet#87]
I recently started trying to use Cabernet and I have run into some issues. I downloaded the source and created the data folder. Once I do that, I start up the tvh_main.py file. Once I go to the Web UI on port 6077 I look to add plug ins, and they install and I restart. Once done, non show up on the homepage, and I can't seem to interact with any. Is there something that I am doing wrong? Any help is greatly appreciated. I am attempting all of this on a mac.

**Comment by rocky4546** [comment]
See #78
