### ISSUE TITLE
PlutoTV instance

### ISSUE THREAD

**Issue by qehs244** [cabernetwork/cabernet#9]
I have configured Cabernet Version: 0.9.7.0 as per instructions and created the mux's in tvheadend and most of them play, epg is in tvheadend (HTS Tvheadend 4.3-1991~g3ed76138a) etc. 

When I go to  record a plutotv stream it will record until it hits the first advertistment break after that nothing and/or it creates a relatively small DVR file of around 100MB, sometimes it will record the entire stream but without sound, or it will record the entire stream with sound until the first advertisment break then the rest is recorded video but no sound. it's very bizarre behaviour and it's not consistent.

Usually it records in TVheadend and you can see the file size increasing but then it abruptly stops but you can see the actual subscription still ticking by with data, but nothing gets recorded.

I'm recording and transcoding into an mkv file, does the stream require any particular type of container like TS or MKV ? I'm not sure if this is a cabernet issue or tvheadend issue.

**Comment by qehs244** [comment]
I'm testing on the baywatch channel as it's back to back the same programs ......

this gets thrown in TVheadend before it stops 

tvheadend[37823]: parser: Pluto-TV/channels.m3u - 400 Baywatch/Service01: H264 @ #256: DTS and PCR diff is very big (18075000)

**Comment by qehs244** [comment]
then this over and over

tvheadend[37823]: TS: Pluto-TV/channels.m3u - 400 Baywatch/Service01: H264 @ #256 Continuity counter error (total 10)

**Comment by qehs244** [comment]
Jan 20 10:50:14 qehs-tv tvheadend[37823]: libav: AVCodecContext: concealing 3593 DC, 3593 AC, 3593 MV errors in I frame
Jan 20 10:50:14 qehs-tv tvheadend[37823]: transcode: 0008: 01:H264: [h264 => libx264]: Invalid pts (69000) <= last (18081000), dropping frame
Jan 20 10:50:14 qehs-tv tvheadend[37823]: libav: AVCodecContext: error while decoding MB 56 0, bytestream -56
Jan 20 10:50:14 qehs-tv tvheadend[37823]: libav: AVCodecContext: concealing 3593 DC, 3593 AC, 3593 MV errors in I frame
Jan 20 10:50:14 qehs-tv tvheadend[37823]: transcode: 0008: 01:H264: [h264 => libx264]: Invalid pts (69000) <= last (18081000), dropping frame
Jan 20 10:50:14 qehs-tv tvheadend[37823]: tsfix: transport stream H264, DTS discontinuity. DTS = 18522000, last = 63000
Jan 20 10:50:14 qehs-tv tvheadend[37823]: transcode: 0008: 01:H264: [h264 => libx264]: Invalid pts (69000) <= last (18081000), dropping frame
Jan 20 10:50:14 qehs-tv tvheadend[37823]: transcode: 0008: 01:H264: [h264 => libx264]: Invalid pts (69000) <= last (18081000), dropping frame
Jan 20 10:50:14 qehs-tv tvheadend[37823]: tsfix: transport stream AAC, DTS discontinuity. DTS = 18529440, last = 18061680

after a restart of cabernet the stream restarts

**Comment by rocky4546** [comment]
It looks like you have configured plutotv incorrectly.  Configuration is based on what the provider streams, today.  In PlutoTV case, it throws ads with incorrect timestamps into the mix causing the errors you see in the logs.  You can either remove the ads or resync the PTS/DTS timestamps.  By default, we use a URL Filter to filter out the ads.  Use the following instance config:
- Enabled: checked
- Enable URL Filtering: checked
- URL Filter: default setting
- XMLTV Enabled: checked
- All other check boxes unchecked
- You can set the EPG settings how you need based on the instances you are trying, but they are optional.

**Comment by rocky4546** [comment]
Data configuration provided for PlutoTV, issue closed.
