### ISSUE TITLE
New to Cabernetwork

### ISSUE THREAD

**Issue by DevanDrake99** [cabernetwork/cabernet#92]
I came from Interlark USTVGO to M3U, and I want to get the DaddyLive channels to work. I have Python already installed, but when I click on the IP address link, it just shows up the error. I followed the instructions clearly. What did I do wrong? I tested the link on Jellyfin, but it wouldn't work either.

**Comment by rocky4546** [comment]
Since it is almost impossible to mess up the website, you are really not following the instructions.  What OS are you using and what version of python?  When you run the "python3 tvh_main.py" command from the command line, do you get any errors and what are they?  When you type in the location field in your browser, what exact IP address do you enter? and what is the exact URL.

**Comment by DevanDrake99** [comment]
> Since it is almost impossible to mess up the website, you are really not following the instructions. What OS are you using and what version of python? When you run the "python3 tvh_main.py" command from the command line, do you get any errors and what are they? When you type in the location field in your browser, what exact IP address do you enter? and what is the exact URL.

I'm using Microsoft Windows 10 and Firefox.

**Comment by DevanDrake99** [comment]
> Since it is almost impossible to mess up the website, you are really not following the instructions. What OS are you using and what version of python? When you run the "python3 tvh_main.py" command from the command line, do you get any errors and what are they? When you type in the location field in your browser, what exact IP address do you enter? and what is the exact URL.

Python version 3.9.5

**Comment by DevanDrake99** [comment]
2023-05-28 13:12:26,737-WARNING:main #########################################
2023-05-28 13:12:26,737-WARNING:main MIT License, Copyright (C) 2021 ROCKY4546

It's what's showing on Python.

**Comment by DevanDrake99** [comment]
I entered my own IP address but it only leads to a Google search rather than an http page.

**Comment by DevanDrake99** [comment]
Never mind. I only typed http://ipaddress:6077/ instead of actually including my IP address. It works now.

**Comment by DevanDrake99** [comment]
Why aren't the channels showing up?

> Since it is almost impossible to mess up the website, you are really not following the instructions. What OS are you using and what version of python? When you run the "python3 tvh_main.py" command from the command line, do you get any errors and what are they? When you type in the location field in your browser, what exact IP address do you enter? and what is the exact URL.

I'm not getting the channels. It's generating nothing.

**Comment by DevanDrake99** [comment]
It shows up an error. 501 - Not Implemented

**Comment by DevanDrake99** [comment]
![image](https://github.com/cabernetwork/cabernet/assets/103958337/b49f5792-ff11-414e-af4a-1b1114435bde)

**Comment by DevanDrake99** [comment]
Never mind that either. I didn't paid attention to the log. I had to close the python file and reopening it, and it completely works. Now I can get the channels to work on Jellyfin. Thank you Rocky.

**Comment by rocky4546** [comment]
501 = not implemented means you gave it a url that means nothing to Cabernet.  you will need to provide the exact URL, if you want help.

The tuner status and scheduler status is going to be empty most of the time, so the image is fine.

Although I can help you through getting it up, you may want to see #78.  It has all the information needed to get all plugins up and running with Jellyfin.  I suspect you have not completed the instructions which state:
  Enable the PlutoTV instance in the Settings page
  Restart the app (from the Scheduler/Applications) to have the plugin fully activate
