### ISSUE TITLE
New version problem

### ISSUE THREAD

**Issue by DevanDrake99** [cabernetwork/cabernet#94]
I'm now having a new problem, whenever I hit save on the Channel Editor, it shows up this message. ERROR: Starting Ch Number setting is not default (-1) [302][default][display_number] not changed

Is there any way to fix this?

**Comment by rocky4546** [comment]
That is the change I put in for people making changes that cause issues to stop it from happening.  You have the Starting Ch Number NOT set to -1 (the default) which means you want Cabernet to manage the channel numbers AND you are also saying you want Cabernet to NOT manage the channel numbers by doing manual changes.  So basically MAKE A CHOICE.  If you want manual editing, then go to the setting and change the Starting Ch Number setting back to default.  You can do this by clearing the field and clicking save changes.

**Comment by DevanDrake99** [comment]
I meant that I want to edit the channel numbers to to emulate the channel numbers from the actual cable service providers or DIRECTV. Like for example, I want Disney Channel on channel 291 instead of channel 99.
